// Catalog of connectable services shown in Apps and Settings.
//
// TRUTHFULNESS CONTRACT
// `status` must describe what a signed-in user can actually do today:
//   - "live"            an end-to-end connect/disconnect flow exists in this app
//                       and works against the production deployment.
//   - "setup_required"  the integration code exists but the deployment must
//                       supply credentials before a user can connect.
//   - "planned"         catalog listing only. No connect flow exists. The UI
//                       must never render an actionable control for these.
// Never mark an entry "live" to make the catalog look bigger.

export type ConnectorStatus = "live" | "setup_required" | "planned";

export type ConnectorCategory =
  | "Productivity"
  | "Email"
  | "Storage & Files"
  | "Calendar"
  | "Education"
  | "Communication"
  | "Notes & Docs"
  | "Social & Media"
  | "Development";

export type ConnectorItem = {
  id: string;
  label: string;
  description: string;
  category: ConnectorCategory;
  status: ConnectorStatus;
  /** Domain used to fetch a brand logo via Logo.dev. */
  domain: string;
  legacyProvider?: "google" | "google-drive" | "gmail" | "youtube" | "apple";
};

export const CONNECTOR_CATALOG: ConnectorItem[] = [
  {
    id: "google",
    label: "Google",
    description: "Sign in with your Google account.",
    category: "Productivity",
    status: "live",
    domain: "google.com",
    legacyProvider: "google",
  },
  {
    id: "gmail",
    label: "Gmail",
    description: "Read message context from Gmail.",
    category: "Email",
    status: "live",
    domain: "gmail.com",
    legacyProvider: "gmail",
  },
  {
    id: "google-drive",
    label: "Google Drive",
    description: "Reference files from your Drive.",
    category: "Storage & Files",
    status: "live",
    domain: "drive.google.com",
    legacyProvider: "google-drive",
  },
  {
    id: "youtube",
    label: "YouTube",
    description: "Reference your YouTube activity.",
    category: "Social & Media",
    status: "planned",
    domain: "youtube.com",
    legacyProvider: "youtube",
  },
  {
    id: "apple",
    label: "Apple",
    description: "Sign in with your Apple ID.",
    category: "Productivity",
    status: "planned",
    domain: "apple.com",
    legacyProvider: "apple",
  },
  {
    id: "outlook",
    label: "Outlook",
    description: "Read Microsoft Outlook mail.",
    category: "Email",
    status: "planned",
    domain: "outlook.com",
  },
  {
    id: "icloud-mail",
    label: "iCloud Mail",
    description: "Read iCloud mail.",
    category: "Email",
    status: "planned",
    domain: "icloud.com",
  },
  {
    id: "yahoo-mail",
    label: "Yahoo Mail",
    description: "Read Yahoo mail.",
    category: "Email",
    status: "planned",
    domain: "yahoo.com",
  },
  {
    id: "proton-mail",
    label: "Proton Mail",
    description: "Read Proton mail.",
    category: "Email",
    status: "planned",
    domain: "proton.me",
  },
  {
    id: "onedrive",
    label: "OneDrive",
    description: "Reference files from OneDrive.",
    category: "Storage & Files",
    status: "planned",
    domain: "onedrive.live.com",
  },
  {
    id: "dropbox",
    label: "Dropbox",
    description: "Reference files from Dropbox.",
    category: "Storage & Files",
    status: "planned",
    domain: "dropbox.com",
  },
  {
    id: "icloud-drive",
    label: "iCloud Drive",
    description: "Reference files from iCloud.",
    category: "Storage & Files",
    status: "planned",
    domain: "icloud.com",
  },
  {
    id: "box",
    label: "Box",
    description: "Reference files from Box.",
    category: "Storage & Files",
    status: "planned",
    domain: "box.com",
  },
  {
    id: "google-calendar",
    label: "Google Calendar",
    description: "Read and create events.",
    category: "Calendar",
    status: "live",
    domain: "calendar.google.com",
  },
  {
    id: "outlook-calendar",
    label: "Outlook Calendar",
    description: "Read and create events.",
    category: "Calendar",
    status: "planned",
    domain: "outlook.com",
  },
  {
    id: "apple-calendar",
    label: "Apple Calendar",
    description: "Read and create events.",
    category: "Calendar",
    status: "planned",
    domain: "apple.com",
  },
  {
    id: "notion",
    label: "Notion",
    description: "Read and update Notion pages.",
    category: "Notes & Docs",
    status: "planned",
    domain: "notion.so",
  },
  {
    id: "google-docs",
    label: "Google Docs",
    description: "Read and edit Docs.",
    category: "Notes & Docs",
    status: "planned",
    domain: "docs.google.com",
  },
  {
    id: "google-sheets",
    label: "Google Sheets",
    description: "Read and update Sheets.",
    category: "Notes & Docs",
    status: "planned",
    domain: "sheets.google.com",
  },
  {
    id: "ms-word",
    label: "Microsoft Word",
    description: "Read and edit Word docs.",
    category: "Notes & Docs",
    status: "planned",
    domain: "microsoft.com",
  },
  {
    id: "ms-excel",
    label: "Microsoft Excel",
    description: "Read and update Excel.",
    category: "Notes & Docs",
    status: "planned",
    domain: "microsoft.com",
  },
  {
    id: "evernote",
    label: "Evernote",
    description: "Read Evernote notes.",
    category: "Notes & Docs",
    status: "planned",
    domain: "evernote.com",
  },
  {
    id: "obsidian",
    label: "Obsidian",
    description: "Sync Obsidian vaults.",
    category: "Notes & Docs",
    status: "planned",
    domain: "obsidian.md",
  },
  {
    id: "apple-notes",
    label: "Apple Notes",
    description: "Read Apple Notes.",
    category: "Notes & Docs",
    status: "planned",
    domain: "apple.com",
  },
  {
    id: "slack",
    label: "Slack",
    description: "Read channels and DMs you allow.",
    category: "Communication",
    status: "planned",
    domain: "slack.com",
  },
  {
    id: "ms-teams",
    label: "Microsoft Teams",
    description: "Read Teams chats.",
    category: "Communication",
    status: "planned",
    domain: "teams.microsoft.com",
  },
  {
    id: "discord",
    label: "Discord",
    description: "Read allowed Discord servers.",
    category: "Communication",
    status: "planned",
    domain: "discord.com",
  },
  {
    id: "whatsapp",
    label: "WhatsApp",
    description: "Connect WhatsApp Business.",
    category: "Communication",
    status: "planned",
    domain: "whatsapp.com",
  },
  {
    id: "telegram",
    label: "Telegram",
    description: "Connect Telegram bot.",
    category: "Communication",
    status: "planned",
    domain: "telegram.org",
  },
  {
    id: "zoom",
    label: "Zoom",
    description: "Read meeting transcripts.",
    category: "Communication",
    status: "planned",
    domain: "zoom.us",
  },
  {
    id: "trello",
    label: "Trello",
    description: "Read your boards.",
    category: "Productivity",
    status: "planned",
    domain: "trello.com",
  },
  {
    id: "asana",
    label: "Asana",
    description: "Read tasks and projects.",
    category: "Productivity",
    status: "planned",
    domain: "asana.com",
  },
  {
    id: "linear",
    label: "Linear",
    description: "Read issues and projects.",
    category: "Productivity",
    status: "planned",
    domain: "linear.app",
  },
  {
    id: "todoist",
    label: "Todoist",
    description: "Read and update tasks.",
    category: "Productivity",
    status: "planned",
    domain: "todoist.com",
  },
  {
    id: "monday",
    label: "Monday.com",
    description: "Read your boards.",
    category: "Productivity",
    status: "planned",
    domain: "monday.com",
  },
  {
    id: "jira",
    label: "Jira",
    description: "Read issues and sprints.",
    category: "Productivity",
    status: "planned",
    domain: "atlassian.com",
  },
  {
    id: "clickup",
    label: "ClickUp",
    description: "Read tasks and docs.",
    category: "Productivity",
    status: "planned",
    domain: "clickup.com",
  },
  {
    id: "google-classroom",
    label: "Google Classroom",
    description: "Read assignments and classes.",
    category: "Education",
    status: "planned",
    domain: "classroom.google.com",
  },
  {
    id: "canvas",
    label: "Canvas LMS",
    description: "Read courses and grades.",
    category: "Education",
    status: "planned",
    domain: "instructure.com",
  },
  {
    id: "schoology",
    label: "Schoology",
    description: "Read courses and grades.",
    category: "Education",
    status: "planned",
    domain: "schoology.com",
  },
  {
    id: "powerschool",
    label: "PowerSchool",
    description: "Read grades and schedules.",
    category: "Education",
    status: "planned",
    domain: "powerschool.com",
  },
  {
    id: "khan-academy",
    label: "Khan Academy",
    description: "Sync progress and recommendations.",
    category: "Education",
    status: "planned",
    domain: "khanacademy.org",
  },
  {
    id: "duolingo",
    label: "Duolingo",
    description: "Sync your learning streak.",
    category: "Education",
    status: "planned",
    domain: "duolingo.com",
  },
  {
    id: "quizlet",
    label: "Quizlet",
    description: "Read study sets.",
    category: "Education",
    status: "planned",
    domain: "quizlet.com",
  },
  {
    id: "tiktok",
    label: "TikTok",
    description: "Reference saved content.",
    category: "Social & Media",
    status: "planned",
    domain: "tiktok.com",
  },
  {
    id: "instagram",
    label: "Instagram",
    description: "Reference saved posts.",
    category: "Social & Media",
    status: "planned",
    domain: "instagram.com",
  },
  {
    id: "x-twitter",
    label: "X (Twitter)",
    description: "Reference bookmarks.",
    category: "Social & Media",
    status: "planned",
    domain: "x.com",
  },
  {
    id: "reddit",
    label: "Reddit",
    description: "Reference saved posts.",
    category: "Social & Media",
    status: "planned",
    domain: "reddit.com",
  },
  {
    id: "linkedin",
    label: "LinkedIn",
    description: "Reference your profile.",
    category: "Social & Media",
    status: "planned",
    domain: "linkedin.com",
  },
  {
    id: "spotify",
    label: "Spotify",
    description: "Reference your playlists.",
    category: "Social & Media",
    status: "planned",
    domain: "spotify.com",
  },
  {
    id: "apple-music",
    label: "Apple Music",
    description: "Reference your library.",
    category: "Social & Media",
    status: "planned",
    domain: "music.apple.com",
  },
  {
    id: "pinterest",
    label: "Pinterest",
    description: "Reference your boards.",
    category: "Social & Media",
    status: "planned",
    domain: "pinterest.com",
  },
  {
    id: "github",
    label: "GitHub",
    description: "Read repos and issues.",
    category: "Development",
    status: "setup_required",
    domain: "github.com",
  },
  {
    id: "gitlab",
    label: "GitLab",
    description: "Read repos and issues.",
    category: "Development",
    status: "planned",
    domain: "gitlab.com",
  },
  {
    id: "vercel",
    label: "Vercel",
    description: "Read deployments.",
    category: "Development",
    status: "planned",
    domain: "vercel.com",
  },
  {
    id: "stripe",
    label: "Stripe",
    description: "Read payment summaries.",
    category: "Development",
    status: "planned",
    domain: "stripe.com",
  },
  {
    id: "clever",
    label: "Clever",
    description: "Check class apps, assignments, and school resources.",
    category: "Education",
    status: "planned",
    domain: "clever.com",
  },
  {
    id: "classlink",
    label: "ClassLink",
    description: "Check LaunchPad apps, classes, and school tasks.",
    category: "Education",
    status: "planned",
    domain: "classlink.com",
  },
  {
    id: "blackboard",
    label: "Blackboard Learn",
    description: "Check courses, assignments, grades, and messages.",
    category: "Education",
    status: "planned",
    domain: "blackboard.com",
  },
  {
    id: "moodle",
    label: "Moodle",
    description: "Check courses, assignments, grades, and feedback.",
    category: "Education",
    status: "planned",
    domain: "moodle.org",
  },
  {
    id: "d2l-brightspace",
    label: "D2L Brightspace",
    description: "Check coursework, grades, quizzes, and due dates.",
    category: "Education",
    status: "planned",
    domain: "d2l.com",
  },
  {
    id: "edmodo",
    label: "Edmodo",
    description: "Check class posts, assignments, and resources.",
    category: "Education",
    status: "planned",
    domain: "edmodo.com",
  },
  {
    id: "seesaw",
    label: "Seesaw",
    description: "Check student activities, messages, and class work.",
    category: "Education",
    status: "planned",
    domain: "seesaw.me",
  },
  {
    id: "edpuzzle",
    label: "Edpuzzle",
    description: "Check video lessons, questions, and class assignments.",
    category: "Education",
    status: "planned",
    domain: "edpuzzle.com",
  },
  {
    id: "nearpod",
    label: "Nearpod",
    description: "Check interactive lessons and assigned activities.",
    category: "Education",
    status: "planned",
    domain: "nearpod.com",
  },
  {
    id: "pear-deck",
    label: "Pear Deck",
    description: "Check interactive classroom lessons and assignments.",
    category: "Education",
    status: "planned",
    domain: "peardeck.com",
  },
  {
    id: "formative",
    label: "Formative",
    description: "Check class activities, quizzes, and teacher feedback.",
    category: "Education",
    status: "planned",
    domain: "goformative.com",
  },
  {
    id: "newsela",
    label: "Newsela",
    description: "Check reading assignments and class articles.",
    category: "Education",
    status: "planned",
    domain: "newsela.com",
  },
  {
    id: "commonlit",
    label: "CommonLit",
    description: "Check reading lessons, assignments, and progress.",
    category: "Education",
    status: "planned",
    domain: "commonlit.org",
  },
  {
    id: "readworks",
    label: "ReadWorks",
    description: "Check reading passages, assignments, and questions.",
    category: "Education",
    status: "planned",
    domain: "readworks.org",
  },
  {
    id: "achieve3000",
    label: "Achieve3000",
    description: "Check literacy assignments and progress.",
    category: "Education",
    status: "planned",
    domain: "achieve3000.com",
  },
  {
    id: "ixl",
    label: "IXL",
    description: "Check skill practice, recommendations, and progress.",
    category: "Education",
    status: "planned",
    domain: "ixl.com",
  },
  {
    id: "i-ready",
    label: "i Ready",
    description: "Check lessons, diagnostics, and assignments.",
    category: "Education",
    status: "planned",
    domain: "i-ready.com",
  },
  {
    id: "renaissance",
    label: "Renaissance",
    description: "Check Accelerated Reader, STAR, and learning progress.",
    category: "Education",
    status: "planned",
    domain: "renaissance.com",
  },
  {
    id: "myon",
    label: "myON",
    description: "Check reading lists, assignments, and progress.",
    category: "Education",
    status: "planned",
    domain: "myon.com",
  },
  {
    id: "epic",
    label: "Epic",
    description: "Check student reading, collections, and progress.",
    category: "Education",
    status: "planned",
    domain: "getepic.com",
  },
  {
    id: "brainpop",
    label: "BrainPOP",
    description: "Check videos, quizzes, and class activities.",
    category: "Education",
    status: "planned",
    domain: "brainpop.com",
  },
  {
    id: "discovery-education",
    label: "Discovery Education",
    description: "Check digital lessons, videos, and assignments.",
    category: "Education",
    status: "planned",
    domain: "discoveryeducation.com",
  },
  {
    id: "ck12",
    label: "CK 12",
    description: "Check FlexBooks, practice, and lessons.",
    category: "Education",
    status: "planned",
    domain: "ck12.org",
  },
  {
    id: "desmos",
    label: "Desmos",
    description: "Check math activities and classroom assignments.",
    category: "Education",
    status: "planned",
    domain: "desmos.com",
  },
  {
    id: "delta-math",
    label: "DeltaMath",
    description: "Check math assignments, practice, and due dates.",
    category: "Education",
    status: "planned",
    domain: "deltamath.com",
  },
  {
    id: "mathspace",
    label: "Mathspace",
    description: "Check math tasks, lessons, and feedback.",
    category: "Education",
    status: "planned",
    domain: "mathspace.co",
  },
  {
    id: "big-ideas-math",
    label: "Big Ideas Math",
    description: "Check math homework, lessons, and resources.",
    category: "Education",
    status: "planned",
    domain: "bigideasmath.com",
  },
  {
    id: "savvas-realize",
    label: "Savvas Realize",
    description: "Check class assignments, books, and assessments.",
    category: "Education",
    status: "planned",
    domain: "savvasrealize.com",
  },
  {
    id: "pearson-realize",
    label: "Pearson Realize",
    description: "Check Pearson coursework and digital assignments.",
    category: "Education",
    status: "planned",
    domain: "pearsonrealize.com",
  },
  {
    id: "mcgraw-hill-connect",
    label: "McGraw Hill Connect",
    description: "Check coursework, homework, and grades.",
    category: "Education",
    status: "planned",
    domain: "mheducation.com",
  },
  {
    id: "hmh-ed",
    label: "HMH Ed",
    description: "Check HMH assignments, lessons, and resources.",
    category: "Education",
    status: "planned",
    domain: "hmhco.com",
  },
  {
    id: "studysync",
    label: "StudySync",
    description: "Check ELA lessons, assignments, and feedback.",
    category: "Education",
    status: "planned",
    domain: "studysync.com",
  },
  {
    id: "edmentum",
    label: "Edmentum",
    description: "Check online courses, assignments, and progress.",
    category: "Education",
    status: "planned",
    domain: "edmentum.com",
  },
  {
    id: "apex-learning",
    label: "Apex Learning",
    description: "Check courses, quizzes, and remaining work.",
    category: "Education",
    status: "planned",
    domain: "apexlearning.com",
  },
  {
    id: "flvs",
    label: "Florida Virtual School",
    description: "Check online classes, assignments, and grades.",
    category: "Education",
    status: "planned",
    domain: "flvs.net",
  },
  {
    id: "edgenuity",
    label: "Edgenuity",
    description: "Check courses, activities, and progress.",
    category: "Education",
    status: "planned",
    domain: "edgenuity.com",
  },
  {
    id: "imagine-learning",
    label: "Imagine Learning",
    description: "Check lessons, assessments, and progress.",
    category: "Education",
    status: "planned",
    domain: "imaginelearning.com",
  },
  {
    id: "naviance",
    label: "Naviance",
    description: "Check college planning tasks and school goals.",
    category: "Education",
    status: "planned",
    domain: "naviance.com",
  },
  {
    id: "schooLinks",
    label: "SchooLinks",
    description: "Check college and career planning tasks.",
    category: "Education",
    status: "planned",
    domain: "schoolinks.com",
  },
  {
    id: "majorclarity",
    label: "MajorClarity",
    description: "Check career planning lessons and assignments.",
    category: "Education",
    status: "planned",
    domain: "majorclarity.com",
  },
  {
    id: "scoir",
    label: "Scoir",
    description: "Check college planning steps and messages.",
    category: "Education",
    status: "planned",
    domain: "scoir.com",
  },
  {
    id: "xello",
    label: "Xello",
    description: "Check career lessons, plans, and assigned tasks.",
    category: "Education",
    status: "planned",
    domain: "xello.world",
  },
  {
    id: "turnitin",
    label: "Turnitin",
    description: "Check submissions, feedback, and originality reports.",
    category: "Education",
    status: "planned",
    domain: "turnitin.com",
  },
  {
    id: "gradescope",
    label: "Gradescope",
    description: "Check submissions, rubrics, and grading feedback.",
    category: "Education",
    status: "planned",
    domain: "gradescope.com",
  },
  {
    id: "examsoft",
    label: "ExamSoft",
    description: "Check exams, results, and assessment tasks.",
    category: "Education",
    status: "planned",
    domain: "examsoft.com",
  },
  {
    id: "respondus",
    label: "Respondus",
    description: "Check online testing tools and assessment requirements.",
    category: "Education",
    status: "planned",
    domain: "respondus.com",
  },
  {
    id: "lockdown-browser",
    label: "LockDown Browser",
    description: "Check secure testing requirements.",
    category: "Education",
    status: "planned",
    domain: "respondus.com",
  },
  {
    id: "college-board",
    label: "College Board",
    description: "Check AP, SAT, and assignment resources.",
    category: "Education",
    status: "planned",
    domain: "collegeboard.org",
  },
  {
    id: "ap-classroom",
    label: "AP Classroom",
    description: "Check AP assignments, progress checks, and resources.",
    category: "Education",
    status: "planned",
    domain: "apclassroom.collegeboard.org",
  },
  {
    id: "act",
    label: "ACT",
    description: "Check test prep, registration, and score resources.",
    category: "Education",
    status: "planned",
    domain: "act.org",
  },
  {
    id: "sat-suite",
    label: "SAT Suite",
    description: "Check SAT practice and readiness tasks.",
    category: "Education",
    status: "planned",
    domain: "satsuite.collegeboard.org",
  },
  {
    id: "pbis-rewards",
    label: "PBIS Rewards",
    description: "Check school behavior points and goals.",
    category: "Education",
    status: "planned",
    domain: "pbisrewards.com",
  },
  {
    id: "classdojo",
    label: "ClassDojo",
    description: "Check class messages, points, and student updates.",
    category: "Education",
    status: "planned",
    domain: "classdojo.com",
  },
  {
    id: "remind",
    label: "Remind",
    description: "Check school messages, announcements, and tasks.",
    category: "Education",
    status: "planned",
    domain: "remind.com",
  },
  {
    id: "parentsquare",
    label: "ParentSquare",
    description: "Check school announcements, messages, and forms.",
    category: "Education",
    status: "planned",
    domain: "parentsquare.com",
  },
  {
    id: "bloomz",
    label: "Bloomz",
    description: "Check class updates, events, and messages.",
    category: "Education",
    status: "planned",
    domain: "bloomz.com",
  },
  {
    id: "talkingpoints",
    label: "TalkingPoints",
    description: "Check teacher messages and school updates.",
    category: "Education",
    status: "planned",
    domain: "talkingpts.org",
  },
  {
    id: "skyward",
    label: "Skyward",
    description: "Check grades, attendance, and missing work.",
    category: "Education",
    status: "planned",
    domain: "skyward.com",
  },
  {
    id: "infinite-campus",
    label: "Infinite Campus",
    description: "Check grades, attendance, and classwork.",
    category: "Education",
    status: "planned",
    domain: "infinitecampus.com",
  },
  {
    id: "aeries",
    label: "Aeries",
    description: "Check grades, attendance, and assignments.",
    category: "Education",
    status: "planned",
    domain: "aeries.com",
  },
  {
    id: "eschoolplus",
    label: "eSchoolPLUS",
    description: "Check grades, attendance, and schedules.",
    category: "Education",
    status: "planned",
    domain: "powerschool.com",
  },
  {
    id: "studentvue",
    label: "StudentVUE",
    description: "Check grades, attendance, and missing assignments.",
    category: "Education",
    status: "planned",
    domain: "edupoint.com",
  },
  {
    id: "parentvue",
    label: "ParentVUE",
    description: "Check student grades, attendance, and assignments.",
    category: "Education",
    status: "planned",
    domain: "edupoint.com",
  },
  {
    id: "renweb",
    label: "FACTS SIS",
    description: "Check school grades, assignments, and billing.",
    category: "Education",
    status: "planned",
    domain: "factsmgt.com",
  },
  {
    id: "alma",
    label: "Alma SIS",
    description: "Check grades, assignments, and school updates.",
    category: "Education",
    status: "planned",
    domain: "getalma.com",
  },
  {
    id: "jupiter",
    label: "Jupiter Ed",
    description: "Check grades, assignments, and class messages.",
    category: "Education",
    status: "planned",
    domain: "jupitered.com",
  },
  {
    id: "teacherease",
    label: "TeacherEase",
    description: "Check grades, assignments, and standards progress.",
    category: "Education",
    status: "planned",
    domain: "teacherease.com",
  },
  {
    id: "classtag",
    label: "ClassTag",
    description: "Check classroom updates, events, and messages.",
    category: "Education",
    status: "planned",
    domain: "classtag.com",
  },
  {
    id: "kickboard",
    label: "Kickboard",
    description: "Check behavior progress and classroom goals.",
    category: "Education",
    status: "planned",
    domain: "kickboardforschools.com",
  },
  {
    id: "go-guardian",
    label: "GoGuardian",
    description: "Check school device learning activity and reports.",
    category: "Education",
    status: "planned",
    domain: "goguardian.com",
  },
  {
    id: "hapara",
    label: "Hapara",
    description: "Check digital classroom tasks and resources.",
    category: "Education",
    status: "planned",
    domain: "hapara.com",
  },
  {
    id: "socrative",
    label: "Socrative",
    description: "Check quizzes, exit tickets, and classroom activities.",
    category: "Education",
    status: "planned",
    domain: "socrative.com",
  },
  {
    id: "kahoot",
    label: "Kahoot",
    description: "Check assigned games and study challenges.",
    category: "Education",
    status: "planned",
    domain: "kahoot.com",
  },
  {
    id: "blooket",
    label: "Blooket",
    description: "Check study games and class assignments.",
    category: "Education",
    status: "planned",
    domain: "blooket.com",
  },
  {
    id: "gimkit",
    label: "Gimkit",
    description: "Check class kits, assignments, and progress.",
    category: "Education",
    status: "planned",
    domain: "gimkit.com",
  },
  {
    id: "nearpod-flocabulary",
    label: "Flocabulary",
    description: "Check vocabulary videos, quizzes, and lessons.",
    category: "Education",
    status: "planned",
    domain: "flocabulary.com",
  },
  {
    id: "quill",
    label: "Quill",
    description: "Check writing and grammar assignments.",
    category: "Education",
    status: "planned",
    domain: "quill.org",
  },
  {
    id: "no-red-ink",
    label: "NoRedInk",
    description: "Check writing practice, quizzes, and assignments.",
    category: "Education",
    status: "planned",
    domain: "noredink.com",
  },
  {
    id: "typing-com",
    label: "Typing.com",
    description: "Check keyboarding lessons and progress.",
    category: "Education",
    status: "planned",
    domain: "typing.com",
  },
  {
    id: "code-org",
    label: "Code.org",
    description: "Check coding lessons, projects, and progress.",
    category: "Education",
    status: "planned",
    domain: "code.org",
  },
  {
    id: "scratch",
    label: "Scratch",
    description: "Check coding projects and class studios.",
    category: "Education",
    status: "planned",
    domain: "scratch.mit.edu",
  },
  {
    id: "codehs",
    label: "CodeHS",
    description: "Check coding courses, assignments, and grades.",
    category: "Education",
    status: "planned",
    domain: "codehs.com",
  },
  {
    id: "replit",
    label: "Replit",
    description: "Check coding projects and classroom assignments.",
    category: "Development",
    status: "planned",
    domain: "replit.com",
  },
  {
    id: "tinkercad",
    label: "Tinkercad",
    description: "Check design projects and classroom activities.",
    category: "Education",
    status: "planned",
    domain: "tinkercad.com",
  },
  {
    id: "typingclub",
    label: "TypingClub",
    description: "Check typing lessons, assignments, and progress.",
    category: "Education",
    status: "planned",
    domain: "typingclub.com",
  },
  {
    id: "membean",
    label: "Membean",
    description: "Check vocabulary sessions and assignments.",
    category: "Education",
    status: "planned",
    domain: "membean.com",
  },
  {
    id: "vocabulary-com",
    label: "Vocabulary.com",
    description: "Check word lists, practice, and assignments.",
    category: "Education",
    status: "planned",
    domain: "vocabulary.com",
  },
  {
    id: "gale",
    label: "Gale",
    description: "Check research databases and saved sources.",
    category: "Education",
    status: "planned",
    domain: "gale.com",
  },
  {
    id: "jstor",
    label: "JSTOR",
    description: "Check research sources and saved materials.",
    category: "Education",
    status: "planned",
    domain: "jstor.org",
  },
  {
    id: "proquest",
    label: "ProQuest",
    description: "Check research databases and saved sources.",
    category: "Education",
    status: "planned",
    domain: "proquest.com",
  },
  {
    id: "ebsco",
    label: "EBSCO",
    description: "Check research articles and saved folders.",
    category: "Education",
    status: "planned",
    domain: "ebsco.com",
  },
  {
    id: "world-book",
    label: "World Book",
    description: "Check research articles and student resources.",
    category: "Education",
    status: "planned",
    domain: "worldbookonline.com",
  },
  {
    id: "britannica-school",
    label: "Britannica School",
    description: "Check encyclopedia research and assignments.",
    category: "Education",
    status: "planned",
    domain: "britannica.com",
  },
  {
    id: "overdrive-sora",
    label: "Sora",
    description: "Check school ebooks, audiobooks, and assignments.",
    category: "Education",
    status: "planned",
    domain: "soraapp.com",
  },
  {
    id: "mackinvia",
    label: "MackinVIA",
    description: "Check school library books and resources.",
    category: "Education",
    status: "planned",
    domain: "mackinvia.com",
  },
  {
    id: "follett-destiny",
    label: "Follett Destiny",
    description: "Check school library resources and checkouts.",
    category: "Education",
    status: "planned",
    domain: "follettdestiny.com",
  },
  {
    id: "peardeck-tutor",
    label: "Pear Deck Tutor",
    description: "Check tutoring sessions and learning support.",
    category: "Education",
    status: "planned",
    domain: "peardecktutor.com",
  },
  {
    id: "paper",
    label: "Paper",
    description: "Check tutoring help and writing feedback.",
    category: "Education",
    status: "planned",
    domain: "paper.co",
  },
  {
    id: "brainly",
    label: "Brainly",
    description: "Check homework help and study answers.",
    category: "Education",
    status: "planned",
    domain: "brainly.com",
  },
  {
    id: "chegg",
    label: "Chegg",
    description: "Check study help, textbooks, and homework support.",
    category: "Education",
    status: "planned",
    domain: "chegg.com",
  },
  {
    id: "course-hero",
    label: "Course Hero",
    description: "Check study guides, documents, and resources.",
    category: "Education",
    status: "planned",
    domain: "coursehero.com",
  },
  {
    id: "airtable",
    label: "Airtable",
    description: "Reference bases, records, and team workflows.",
    category: "Productivity",
    status: "planned",
    domain: "airtable.com",
  },
  {
    id: "figma",
    label: "Figma",
    description: "Reference design files, comments, and prototypes.",
    category: "Productivity",
    status: "planned",
    domain: "figma.com",
  },
  {
    id: "miro",
    label: "Miro",
    description: "Reference boards, diagrams, and brainstorming notes.",
    category: "Productivity",
    status: "planned",
    domain: "miro.com",
  },
  {
    id: "canva",
    label: "Canva",
    description: "Reference designs, brand assets, and presentations.",
    category: "Productivity",
    status: "planned",
    domain: "canva.com",
  },
  {
    id: "adobe",
    label: "Adobe",
    description: "Reference creative files and document assets.",
    category: "Productivity",
    status: "planned",
    domain: "adobe.com",
  },
  {
    id: "zapier",
    label: "Zapier",
    description: "Reference automations and connected workflows.",
    category: "Productivity",
    status: "planned",
    domain: "zapier.com",
  },
  {
    id: "make",
    label: "Make",
    description: "Reference automations, scenarios, and workflow runs.",
    category: "Productivity",
    status: "planned",
    domain: "make.com",
  },
  {
    id: "hubspot",
    label: "HubSpot",
    description: "Reference contacts, companies, and deal context.",
    category: "Productivity",
    status: "planned",
    domain: "hubspot.com",
  },
  {
    id: "salesforce",
    label: "Salesforce",
    description: "Reference CRM accounts, contacts, and opportunities.",
    category: "Productivity",
    status: "planned",
    domain: "salesforce.com",
  },
  {
    id: "zendesk",
    label: "Zendesk",
    description: "Reference tickets, users, and support history.",
    category: "Communication",
    status: "planned",
    domain: "zendesk.com",
  },
  {
    id: "intercom",
    label: "Intercom",
    description: "Reference conversations, leads, and support context.",
    category: "Communication",
    status: "planned",
    domain: "intercom.com",
  },
  {
    id: "freshdesk",
    label: "Freshdesk",
    description: "Reference tickets and customer support context.",
    category: "Communication",
    status: "planned",
    domain: "freshdesk.com",
  },
  {
    id: "front",
    label: "Front",
    description: "Reference shared inboxes and customer messages.",
    category: "Email",
    status: "planned",
    domain: "front.com",
  },
  {
    id: "superhuman",
    label: "Superhuman",
    description: "Reference email context from Superhuman.",
    category: "Email",
    status: "planned",
    domain: "superhuman.com",
  },
  {
    id: "hey",
    label: "HEY",
    description: "Reference email context from HEY.",
    category: "Email",
    status: "planned",
    domain: "hey.com",
  },
  {
    id: "fastmail",
    label: "Fastmail",
    description: "Reference messages and mailbox context.",
    category: "Email",
    status: "planned",
    domain: "fastmail.com",
  },
  {
    id: "mailchimp",
    label: "Mailchimp",
    description: "Reference campaigns, audiences, and reports.",
    category: "Productivity",
    status: "planned",
    domain: "mailchimp.com",
  },
  {
    id: "constant-contact",
    label: "Constant Contact",
    description: "Reference email campaigns and audience lists.",
    category: "Productivity",
    status: "planned",
    domain: "constantcontact.com",
  },
  {
    id: "brevo",
    label: "Brevo",
    description: "Reference campaigns, automations, and contacts.",
    category: "Productivity",
    status: "planned",
    domain: "brevo.com",
  },
  {
    id: "klaviyo",
    label: "Klaviyo",
    description: "Reference customer segments and campaign performance.",
    category: "Productivity",
    status: "planned",
    domain: "klaviyo.com",
  },
  {
    id: "shopify",
    label: "Shopify",
    description: "Reference products, orders, and storefront activity.",
    category: "Productivity",
    status: "planned",
    domain: "shopify.com",
  },
  {
    id: "woocommerce",
    label: "WooCommerce",
    description: "Reference store orders, products, and customers.",
    category: "Productivity",
    status: "planned",
    domain: "woocommerce.com",
  },
  {
    id: "square",
    label: "Square",
    description: "Reference sales, customers, and payment activity.",
    category: "Productivity",
    status: "planned",
    domain: "squareup.com",
  },
  {
    id: "paypal",
    label: "PayPal",
    description: "Reference payments, invoices, and account activity.",
    category: "Productivity",
    status: "planned",
    domain: "paypal.com",
  },
  {
    id: "quickbooks",
    label: "QuickBooks",
    description: "Reference invoices, expenses, and accounting summaries.",
    category: "Productivity",
    status: "planned",
    domain: "quickbooks.intuit.com",
  },
  {
    id: "xero",
    label: "Xero",
    description: "Reference accounting records and business finances.",
    category: "Productivity",
    status: "planned",
    domain: "xero.com",
  },
  {
    id: "wave",
    label: "Wave",
    description: "Reference invoices, receipts, and accounting data.",
    category: "Productivity",
    status: "planned",
    domain: "waveapps.com",
  },
  {
    id: "plaid",
    label: "Plaid",
    description: "Reference connected financial account summaries.",
    category: "Productivity",
    status: "planned",
    domain: "plaid.com",
  },
  {
    id: "robinhood",
    label: "Robinhood",
    description: "Reference brokerage watchlists and portfolio context.",
    category: "Productivity",
    status: "planned",
    domain: "robinhood.com",
  },
  {
    id: "coinbase",
    label: "Coinbase",
    description: "Reference crypto account activity and watchlists.",
    category: "Productivity",
    status: "planned",
    domain: "coinbase.com",
  },
  {
    id: "kraken",
    label: "Kraken",
    description: "Reference crypto portfolio and account activity.",
    category: "Productivity",
    status: "planned",
    domain: "kraken.com",
  },
  {
    id: "notion-calendar",
    label: "Notion Calendar",
    description: "Reference calendar events and schedules.",
    category: "Calendar",
    status: "planned",
    domain: "calendar.notion.so",
  },
  {
    id: "calendly",
    label: "Calendly",
    description: "Reference scheduled meetings and event links.",
    category: "Calendar",
    status: "planned",
    domain: "calendly.com",
  },
  {
    id: "acuity",
    label: "Acuity Scheduling",
    description: "Reference appointments, calendars, and availability.",
    category: "Calendar",
    status: "planned",
    domain: "acuityscheduling.com",
  },
  {
    id: "google-keep",
    label: "Google Keep",
    description: "Reference notes, lists, and reminders.",
    category: "Notes & Docs",
    status: "planned",
    domain: "keep.google.com",
  },
  {
    id: "coda",
    label: "Coda",
    description: "Reference docs, tables, and team workflows.",
    category: "Notes & Docs",
    status: "planned",
    domain: "coda.io",
  },
  {
    id: "quip",
    label: "Quip",
    description: "Reference team docs and collaborative notes.",
    category: "Notes & Docs",
    status: "planned",
    domain: "quip.com",
  },
  {
    id: "slite",
    label: "Slite",
    description: "Reference team docs and workspace knowledge.",
    category: "Notes & Docs",
    status: "planned",
    domain: "slite.com",
  },
  {
    id: "confluence",
    label: "Confluence",
    description: "Reference pages, spaces, and team knowledge.",
    category: "Notes & Docs",
    status: "planned",
    domain: "atlassian.com",
  },
  {
    id: "dropbox-paper",
    label: "Dropbox Paper",
    description: "Reference collaborative docs and notes.",
    category: "Notes & Docs",
    status: "planned",
    domain: "dropbox.com",
  },
  {
    id: "mattermost",
    label: "Mattermost",
    description: "Reference channels, threads, and messages.",
    category: "Communication",
    status: "planned",
    domain: "mattermost.com",
  },
  {
    id: "signal",
    label: "Signal",
    description: "Reference secure messages and conversations.",
    category: "Communication",
    status: "planned",
    domain: "signal.org",
  },
  {
    id: "google-chat",
    label: "Google Chat",
    description: "Reference spaces, threads, and messages.",
    category: "Communication",
    status: "planned",
    domain: "chat.google.com",
  },
  {
    id: "webex",
    label: "Webex",
    description: "Reference meetings, transcripts, and messages.",
    category: "Communication",
    status: "planned",
    domain: "webex.com",
  },
  {
    id: "meet",
    label: "Google Meet",
    description: "Reference meetings, captions, and notes.",
    category: "Communication",
    status: "planned",
    domain: "meet.google.com",
  },
  {
    id: "loom",
    label: "Loom",
    description: "Reference videos, transcripts, and team updates.",
    category: "Communication",
    status: "planned",
    domain: "loom.com",
  },
  {
    id: "otter",
    label: "Otter",
    description: "Reference meeting transcripts and notes.",
    category: "Communication",
    status: "planned",
    domain: "otter.ai",
  },
  {
    id: "fireflies",
    label: "Fireflies.ai",
    description: "Reference call transcripts and meeting summaries.",
    category: "Communication",
    status: "planned",
    domain: "fireflies.ai",
  },
  {
    id: "fathom",
    label: "Fathom",
    description: "Reference meeting recordings and summaries.",
    category: "Communication",
    status: "planned",
    domain: "fathom.video",
  },
  {
    id: "basecamp",
    label: "Basecamp",
    description: "Reference projects, messages, and to dos.",
    category: "Productivity",
    status: "planned",
    domain: "basecamp.com",
  },
  {
    id: "smartsheet",
    label: "Smartsheet",
    description: "Reference sheets, projects, and reports.",
    category: "Productivity",
    status: "planned",
    domain: "smartsheet.com",
  },
  {
    id: "wrike",
    label: "Wrike",
    description: "Reference tasks, projects, and timelines.",
    category: "Productivity",
    status: "planned",
    domain: "wrike.com",
  },
  {
    id: "height",
    label: "Height",
    description: "Reference tasks, projects, and product plans.",
    category: "Productivity",
    status: "planned",
    domain: "height.app",
  },
  {
    id: "shortcut",
    label: "Shortcut",
    description: "Reference stories, epics, and engineering plans.",
    category: "Productivity",
    status: "planned",
    domain: "shortcut.com",
  },
  {
    id: "pivotal-tracker",
    label: "Pivotal Tracker",
    description: "Reference stories, epics, and backlog status.",
    category: "Productivity",
    status: "planned",
    domain: "pivotaltracker.com",
  },
  {
    id: "azure-devops",
    label: "Azure DevOps",
    description: "Reference boards, repos, and pipelines.",
    category: "Development",
    status: "planned",
    domain: "dev.azure.com",
  },
  {
    id: "bitbucket",
    label: "Bitbucket",
    description: "Reference repositories, pull requests, and issues.",
    category: "Development",
    status: "planned",
    domain: "bitbucket.org",
  },
  {
    id: "sentry",
    label: "Sentry",
    description: "Reference issues, releases, and error context.",
    category: "Development",
    status: "planned",
    domain: "sentry.io",
  },
  {
    id: "datadog",
    label: "Datadog",
    description: "Reference dashboards, logs, and incidents.",
    category: "Development",
    status: "planned",
    domain: "datadoghq.com",
  },
  {
    id: "new-relic",
    label: "New Relic",
    description: "Reference observability dashboards and incidents.",
    category: "Development",
    status: "planned",
    domain: "newrelic.com",
  },
  {
    id: "pagerduty",
    label: "PagerDuty",
    description: "Reference incidents, services, and on call schedules.",
    category: "Development",
    status: "planned",
    domain: "pagerduty.com",
  },
  {
    id: "opsgenie",
    label: "Opsgenie",
    description: "Reference alerts, incidents, and schedules.",
    category: "Development",
    status: "planned",
    domain: "atlassian.com",
  },
  {
    id: "circleci",
    label: "CircleCI",
    description: "Reference builds, workflows, and deployments.",
    category: "Development",
    status: "planned",
    domain: "circleci.com",
  },
  {
    id: "github-actions",
    label: "GitHub Actions",
    description: "Reference workflow runs and deployment checks.",
    category: "Development",
    status: "planned",
    domain: "github.com",
  },
  {
    id: "jenkins",
    label: "Jenkins",
    description: "Reference builds, jobs, and deployment logs.",
    category: "Development",
    status: "planned",
    domain: "jenkins.io",
  },
  {
    id: "docker-hub",
    label: "Docker Hub",
    description: "Reference images, repositories, and tags.",
    category: "Development",
    status: "planned",
    domain: "hub.docker.com",
  },
  {
    id: "aws",
    label: "AWS",
    description: "Reference cloud resources, billing, and operational context.",
    category: "Development",
    status: "planned",
    domain: "aws.amazon.com",
  },
  {
    id: "google-cloud",
    label: "Google Cloud",
    description: "Reference cloud resources, logs, and billing.",
    category: "Development",
    status: "planned",
    domain: "cloud.google.com",
  },
  {
    id: "azure",
    label: "Microsoft Azure",
    description: "Reference cloud resources, logs, and billing.",
    category: "Development",
    status: "planned",
    domain: "azure.microsoft.com",
  },
  {
    id: "cloudflare",
    label: "Cloudflare",
    description: "Reference DNS, traffic, and security events.",
    category: "Development",
    status: "planned",
    domain: "cloudflare.com",
  },
  {
    id: "netlify",
    label: "Netlify",
    description: "Reference sites, deploys, and forms.",
    category: "Development",
    status: "planned",
    domain: "netlify.com",
  },
  {
    id: "digitalocean",
    label: "DigitalOcean",
    description: "Reference projects, droplets, and billing.",
    category: "Development",
    status: "planned",
    domain: "digitalocean.com",
  },
  {
    id: "heroku",
    label: "Heroku",
    description: "Reference apps, pipelines, and logs.",
    category: "Development",
    status: "planned",
    domain: "heroku.com",
  },
  {
    id: "mongodb",
    label: "MongoDB",
    description: "Reference databases, clusters, and performance.",
    category: "Development",
    status: "planned",
    domain: "mongodb.com",
  },
  {
    id: "postgres",
    label: "PostgreSQL",
    description: "Reference database metadata and operational context.",
    category: "Development",
    status: "planned",
    domain: "postgresql.org",
  },
  {
    id: "mysql",
    label: "MySQL",
    description: "Reference database metadata and operational context.",
    category: "Development",
    status: "planned",
    domain: "mysql.com",
  },
  {
    id: "redis",
    label: "Redis",
    description: "Reference cache, queues, and database context.",
    category: "Development",
    status: "planned",
    domain: "redis.io",
  },
  {
    id: "supabase",
    label: "Supabase",
    description: "Reference backend tables, auth, and storage context.",
    category: "Development",
    status: "planned",
    domain: "supabase.com",
  },
  {
    id: "firebase",
    label: "Firebase",
    description: "Reference app analytics, auth, and database context.",
    category: "Development",
    status: "planned",
    domain: "firebase.google.com",
  },
  {
    id: "posthog",
    label: "PostHog",
    description: "Reference product analytics and event funnels.",
    category: "Productivity",
    status: "planned",
    domain: "posthog.com",
  },
  {
    id: "mixpanel",
    label: "Mixpanel",
    description: "Reference analytics events, cohorts, and funnels.",
    category: "Productivity",
    status: "planned",
    domain: "mixpanel.com",
  },
  {
    id: "amplitude",
    label: "Amplitude",
    description: "Reference product analytics and experiment data.",
    category: "Productivity",
    status: "planned",
    domain: "amplitude.com",
  },
  {
    id: "google-analytics",
    label: "Google Analytics",
    description: "Reference website analytics and acquisition context.",
    category: "Productivity",
    status: "planned",
    domain: "analytics.google.com",
  },
  {
    id: "google-ads",
    label: "Google Ads",
    description: "Reference campaigns, keywords, and performance.",
    category: "Productivity",
    status: "planned",
    domain: "ads.google.com",
  },
  {
    id: "meta-ads",
    label: "Meta Ads",
    description: "Reference campaigns, audiences, and reports.",
    category: "Productivity",
    status: "planned",
    domain: "facebook.com",
  },
  {
    id: "tiktok-ads",
    label: "TikTok Ads",
    description: "Reference campaigns, audiences, and reports.",
    category: "Productivity",
    status: "planned",
    domain: "ads.tiktok.com",
  },
  {
    id: "linkedin-ads",
    label: "LinkedIn Ads",
    description: "Reference campaigns, audiences, and reports.",
    category: "Productivity",
    status: "planned",
    domain: "linkedin.com",
  },
  {
    id: "youtube-studio",
    label: "YouTube Studio",
    description: "Reference channel analytics, comments, and content.",
    category: "Social & Media",
    status: "planned",
    domain: "studio.youtube.com",
  },
  {
    id: "facebook",
    label: "Facebook",
    description: "Reference pages, posts, and saved content.",
    category: "Social & Media",
    status: "planned",
    domain: "facebook.com",
  },
  {
    id: "threads",
    label: "Threads",
    description: "Reference posts, profile context, and activity.",
    category: "Social & Media",
    status: "planned",
    domain: "threads.net",
  },
  {
    id: "mastodon",
    label: "Mastodon",
    description: "Reference posts, bookmarks, and profile activity.",
    category: "Social & Media",
    status: "planned",
    domain: "joinmastodon.org",
  },
  {
    id: "medium",
    label: "Medium",
    description: "Reference drafts, posts, and reading lists.",
    category: "Social & Media",
    status: "planned",
    domain: "medium.com",
  },
  {
    id: "substack",
    label: "Substack",
    description: "Reference newsletters, posts, and subscribers.",
    category: "Social & Media",
    status: "planned",
    domain: "substack.com",
  },
  {
    id: "twitch",
    label: "Twitch",
    description: "Reference streams, clips, and channel activity.",
    category: "Social & Media",
    status: "planned",
    domain: "twitch.tv",
  },
  {
    id: "vimeo",
    label: "Vimeo",
    description: "Reference videos, analytics, and libraries.",
    category: "Social & Media",
    status: "planned",
    domain: "vimeo.com",
  },
  {
    id: "soundcloud",
    label: "SoundCloud",
    description: "Reference playlists, tracks, and account activity.",
    category: "Social & Media",
    status: "planned",
    domain: "soundcloud.com",
  },
  {
    id: "github-classroom",
    label: "GitHub Classroom",
    description: "Check coding assignments and classroom repositories.",
    category: "Education",
    status: "planned",
    domain: "classroom.github.com",
  },
  {
    id: "acme",
    label: "Acme Workspace",
    description: "Reference tasks, records, and workspace updates.",
    category: "Productivity",
    status: "planned",
    domain: "acme.com",
  },
  {
    id: "tutorbird",
    label: "TutorBird",
    description: "Reference messages, labels, and mailbox context.",
    category: "Email",
    status: "planned",
    domain: "tutorbird.com",
  },
  {
    id: "mystudylife",
    label: "MyStudyLife",
    description: "Reference files, folders, and recent changes.",
    category: "Storage & Files",
    status: "planned",
    domain: "mystudylife.com",
  },
  {
    id: "studysmarter",
    label: "StudySmarter",
    description: "Reference events, due dates, and schedules.",
    category: "Calendar",
    status: "planned",
    domain: "studysmarter.com",
  },
  {
    id: "brilliant",
    label: "Brilliant",
    description: "Reference documents, notes, and shared knowledge.",
    category: "Notes & Docs",
    status: "planned",
    domain: "brilliant.org",
  },
  {
    id: "coursera",
    label: "Coursera",
    description: "Reference messages, channels, and conversation context.",
    category: "Communication",
    status: "planned",
    domain: "coursera.org",
  },
  {
    id: "edx",
    label: "edX",
    description: "Reference posts, saved content, and creator activity.",
    category: "Social & Media",
    status: "planned",
    domain: "edx.org",
  },
  {
    id: "udemy",
    label: "Udemy",
    description: "Reference repos, issues, logs, and deployment context.",
    category: "Development",
    status: "planned",
    domain: "udemy.com",
  },
  {
    id: "skillshare",
    label: "Skillshare",
    description: "Reference assignments, grades, remaining work, and class updates.",
    category: "Education",
    status: "planned",
    domain: "skillshare.com",
  },
  {
    id: "linkedin-learning",
    label: "LinkedIn Learning",
    description: "Reference tasks, records, and workspace updates.",
    category: "Productivity",
    status: "planned",
    domain: "learning.linkedin.com",
  },
  {
    id: "openstax",
    label: "OpenStax",
    description: "Reference messages, labels, and mailbox context.",
    category: "Email",
    status: "planned",
    domain: "openstax.org",
  },
  {
    id: "wolfram-alpha",
    label: "Wolfram Alpha",
    description: "Reference files, folders, and recent changes.",
    category: "Storage & Files",
    status: "planned",
    domain: "wolframalpha.com",
  },
  {
    id: "symbolab",
    label: "Symbolab",
    description: "Reference events, due dates, and schedules.",
    category: "Calendar",
    status: "planned",
    domain: "symbolab.com",
  },
  {
    id: "geogebra",
    label: "GeoGebra",
    description: "Reference documents, notes, and shared knowledge.",
    category: "Notes & Docs",
    status: "planned",
    domain: "geogebra.org",
  },
  {
    id: "mathway",
    label: "Mathway",
    description: "Reference messages, channels, and conversation context.",
    category: "Communication",
    status: "planned",
    domain: "mathway.com",
  },
  {
    id: "photomath",
    label: "Photomath",
    description: "Reference posts, saved content, and creator activity.",
    category: "Social & Media",
    status: "planned",
    domain: "photomath.com",
  },
  {
    id: "grammarly",
    label: "Grammarly",
    description: "Reference repos, issues, logs, and deployment context.",
    category: "Development",
    status: "planned",
    domain: "grammarly.com",
  },
  {
    id: "perplexity",
    label: "Perplexity",
    description: "Reference assignments, grades, remaining work, and class updates.",
    category: "Education",
    status: "planned",
    domain: "perplexity.ai",
  },
  {
    id: "claude",
    label: "Claude",
    description: "Reference tasks, records, and workspace updates.",
    category: "Productivity",
    status: "planned",
    domain: "claude.ai",
  },
  {
    id: "chatgpt",
    label: "ChatGPT",
    description: "Reference messages, labels, and mailbox context.",
    category: "Email",
    status: "planned",
    domain: "chatgpt.com",
  },
  {
    id: "gemini",
    label: "Gemini",
    description: "Reference files, folders, and recent changes.",
    category: "Storage & Files",
    status: "planned",
    domain: "gemini.google.com",
  },
  {
    id: "poe",
    label: "Poe",
    description: "Reference events, due dates, and schedules.",
    category: "Calendar",
    status: "planned",
    domain: "poe.com",
  },
  {
    id: "dropbox-sign",
    label: "Dropbox Sign",
    description: "Reference documents, notes, and shared knowledge.",
    category: "Notes & Docs",
    status: "planned",
    domain: "dropboxsign.com",
  },
  {
    id: "docusign",
    label: "DocuSign",
    description: "Reference messages, channels, and conversation context.",
    category: "Communication",
    status: "planned",
    domain: "docusign.com",
  },
  {
    id: "adobe-acrobat",
    label: "Adobe Acrobat",
    description: "Reference posts, saved content, and creator activity.",
    category: "Social & Media",
    status: "planned",
    domain: "acrobat.adobe.com",
  },
  {
    id: "pdfescape",
    label: "PDFescape",
    description: "Reference repos, issues, logs, and deployment context.",
    category: "Development",
    status: "planned",
    domain: "pdfescape.com",
  },
  {
    id: "smallpdf",
    label: "Smallpdf",
    description: "Reference assignments, grades, remaining work, and class updates.",
    category: "Education",
    status: "planned",
    domain: "smallpdf.com",
  },
  {
    id: "wetransfer",
    label: "WeTransfer",
    description: "Reference tasks, records, and workspace updates.",
    category: "Productivity",
    status: "planned",
    domain: "wetransfer.com",
  },
  {
    id: "mega",
    label: "MEGA",
    description: "Reference messages, labels, and mailbox context.",
    category: "Email",
    status: "planned",
    domain: "mega.io",
  },
  {
    id: "pcloud",
    label: "pCloud",
    description: "Reference files, folders, and recent changes.",
    category: "Storage & Files",
    status: "planned",
    domain: "pcloud.com",
  },
  {
    id: "sync",
    label: "Sync",
    description: "Reference events, due dates, and schedules.",
    category: "Calendar",
    status: "planned",
    domain: "sync.com",
  },
  {
    id: "todo-microsoft",
    label: "Microsoft To Do",
    description: "Reference documents, notes, and shared knowledge.",
    category: "Notes & Docs",
    status: "planned",
    domain: "todo.microsoft.com",
  },
  {
    id: "things",
    label: "Things",
    description: "Reference messages, channels, and conversation context.",
    category: "Communication",
    status: "planned",
    domain: "culturedcode.com",
  },
  {
    id: "omnifocus",
    label: "OmniFocus",
    description: "Reference posts, saved content, and creator activity.",
    category: "Social & Media",
    status: "planned",
    domain: "omnigroup.com",
  },
  {
    id: "remember-the-milk",
    label: "Remember The Milk",
    description: "Reference repos, issues, logs, and deployment context.",
    category: "Development",
    status: "planned",
    domain: "rememberthemilk.com",
  },
  {
    id: "habitica",
    label: "Habitica",
    description: "Reference assignments, grades, remaining work, and class updates.",
    category: "Education",
    status: "planned",
    domain: "habitica.com",
  },
  {
    id: "forest",
    label: "Forest",
    description: "Reference tasks, records, and workspace updates.",
    category: "Productivity",
    status: "planned",
    domain: "forestapp.cc",
  },
  {
    id: "rescuetime",
    label: "RescueTime",
    description: "Reference messages, labels, and mailbox context.",
    category: "Email",
    status: "planned",
    domain: "rescuetime.com",
  },
  {
    id: "toggl",
    label: "Toggl",
    description: "Reference files, folders, and recent changes.",
    category: "Storage & Files",
    status: "planned",
    domain: "toggl.com",
  },
  {
    id: "clockify",
    label: "Clockify",
    description: "Reference events, due dates, and schedules.",
    category: "Calendar",
    status: "planned",
    domain: "clockify.me",
  },
  {
    id: "harvest",
    label: "Harvest",
    description: "Reference documents, notes, and shared knowledge.",
    category: "Notes & Docs",
    status: "planned",
    domain: "getharvest.com",
  },
  {
    id: "notability",
    label: "Notability",
    description: "Reference messages, channels, and conversation context.",
    category: "Communication",
    status: "planned",
    domain: "notability.com",
  },
  {
    id: "goodnotes",
    label: "Goodnotes",
    description: "Reference posts, saved content, and creator activity.",
    category: "Social & Media",
    status: "planned",
    domain: "goodnotes.com",
  },
  {
    id: "onenote",
    label: "OneNote",
    description: "Reference repos, issues, logs, and deployment context.",
    category: "Development",
    status: "planned",
    domain: "onenote.com",
  },
  {
    id: "roam",
    label: "Roam Research",
    description: "Reference assignments, grades, remaining work, and class updates.",
    category: "Education",
    status: "planned",
    domain: "roamresearch.com",
  },
  {
    id: "logseq",
    label: "Logseq",
    description: "Reference tasks, records, and workspace updates.",
    category: "Productivity",
    status: "planned",
    domain: "logseq.com",
  },
  {
    id: "readwise",
    label: "Readwise",
    description: "Reference messages, labels, and mailbox context.",
    category: "Email",
    status: "planned",
    domain: "readwise.io",
  },
  {
    id: "pocket",
    label: "Pocket",
    description: "Reference files, folders, and recent changes.",
    category: "Storage & Files",
    status: "planned",
    domain: "getpocket.com",
  },
  {
    id: "instapaper",
    label: "Instapaper",
    description: "Reference events, due dates, and schedules.",
    category: "Calendar",
    status: "planned",
    domain: "instapaper.com",
  },
  {
    id: "raindrop",
    label: "Raindrop.io",
    description: "Reference documents, notes, and shared knowledge.",
    category: "Notes & Docs",
    status: "planned",
    domain: "raindrop.io",
  },
  {
    id: "feedly",
    label: "Feedly",
    description: "Reference messages, channels, and conversation context.",
    category: "Communication",
    status: "planned",
    domain: "feedly.com",
  },
  {
    id: "inoreader",
    label: "Inoreader",
    description: "Reference posts, saved content, and creator activity.",
    category: "Social & Media",
    status: "planned",
    domain: "inoreader.com",
  },
  {
    id: "devto",
    label: "DEV Community",
    description: "Reference repos, issues, logs, and deployment context.",
    category: "Development",
    status: "planned",
    domain: "dev.to",
  },
  {
    id: "stackoverflow",
    label: "Stack Overflow",
    description: "Reference assignments, grades, remaining work, and class updates.",
    category: "Education",
    status: "planned",
    domain: "stackoverflow.com",
  },
  {
    id: "producthunt",
    label: "Product Hunt",
    description: "Reference tasks, records, and workspace updates.",
    category: "Productivity",
    status: "planned",
    domain: "producthunt.com",
  },
  {
    id: "dribbble",
    label: "Dribbble",
    description: "Reference messages, labels, and mailbox context.",
    category: "Email",
    status: "planned",
    domain: "dribbble.com",
  },
  {
    id: "behance",
    label: "Behance",
    description: "Reference files, folders, and recent changes.",
    category: "Storage & Files",
    status: "planned",
    domain: "behance.net",
  },
  {
    id: "unsplash",
    label: "Unsplash",
    description: "Reference events, due dates, and schedules.",
    category: "Calendar",
    status: "planned",
    domain: "unsplash.com",
  },
  {
    id: "pexels",
    label: "Pexels",
    description: "Reference documents, notes, and shared knowledge.",
    category: "Notes & Docs",
    status: "planned",
    domain: "pexels.com",
  },
  {
    id: "figjam",
    label: "FigJam",
    description: "Reference messages, channels, and conversation context.",
    category: "Communication",
    status: "planned",
    domain: "figma.com",
  },
  {
    id: "framer",
    label: "Framer",
    description: "Reference posts, saved content, and creator activity.",
    category: "Social & Media",
    status: "planned",
    domain: "framer.com",
  },
  {
    id: "webflow",
    label: "Webflow",
    description: "Reference repos, issues, logs, and deployment context.",
    category: "Development",
    status: "planned",
    domain: "webflow.com",
  },
  {
    id: "wordpress",
    label: "WordPress",
    description: "Reference assignments, grades, remaining work, and class updates.",
    category: "Education",
    status: "planned",
    domain: "wordpress.com",
  },
  {
    id: "ghost",
    label: "Ghost",
    description: "Reference tasks, records, and workspace updates.",
    category: "Productivity",
    status: "planned",
    domain: "ghost.org",
  },
  {
    id: "wix",
    label: "Wix",
    description: "Reference messages, labels, and mailbox context.",
    category: "Email",
    status: "planned",
    domain: "wix.com",
  },
  {
    id: "squarespace",
    label: "Squarespace",
    description: "Reference files, folders, and recent changes.",
    category: "Storage & Files",
    status: "planned",
    domain: "squarespace.com",
  },
  {
    id: "typeform",
    label: "Typeform",
    description: "Reference events, due dates, and schedules.",
    category: "Calendar",
    status: "planned",
    domain: "typeform.com",
  },
  {
    id: "jotform",
    label: "Jotform",
    description: "Reference documents, notes, and shared knowledge.",
    category: "Notes & Docs",
    status: "planned",
    domain: "jotform.com",
  },
  {
    id: "google-forms",
    label: "Google Forms",
    description: "Reference messages, channels, and conversation context.",
    category: "Communication",
    status: "planned",
    domain: "forms.google.com",
  },
  {
    id: "surveymonkey",
    label: "SurveyMonkey",
    description: "Reference posts, saved content, and creator activity.",
    category: "Social & Media",
    status: "planned",
    domain: "surveymonkey.com",
  },
  {
    id: "qualtrics",
    label: "Qualtrics",
    description: "Reference repos, issues, logs, and deployment context.",
    category: "Development",
    status: "planned",
    domain: "qualtrics.com",
  },
  {
    id: "doodle",
    label: "Doodle",
    description: "Reference assignments, grades, remaining work, and class updates.",
    category: "Education",
    status: "planned",
    domain: "doodle.com",
  },
  {
    id: "when2meet",
    label: "When2meet",
    description: "Reference tasks, records, and workspace updates.",
    category: "Productivity",
    status: "planned",
    domain: "when2meet.com",
  },
  {
    id: "linear-docs",
    label: "Linear Docs",
    description: "Reference messages, labels, and mailbox context.",
    category: "Email",
    status: "planned",
    domain: "linear.app",
  },
  {
    id: "raycast",
    label: "Raycast",
    description: "Reference files, folders, and recent changes.",
    category: "Storage & Files",
    status: "planned",
    domain: "raycast.com",
  },
  {
    id: "alfred",
    label: "Alfred",
    description: "Reference events, due dates, and schedules.",
    category: "Calendar",
    status: "planned",
    domain: "alfredapp.com",
  },
  {
    id: "1password",
    label: "1Password",
    description: "Reference documents, notes, and shared knowledge.",
    category: "Notes & Docs",
    status: "planned",
    domain: "1password.com",
  },
  {
    id: "lastpass",
    label: "LastPass",
    description: "Reference messages, channels, and conversation context.",
    category: "Communication",
    status: "planned",
    domain: "lastpass.com",
  },
  {
    id: "bitwarden",
    label: "Bitwarden",
    description: "Reference posts, saved content, and creator activity.",
    category: "Social & Media",
    status: "planned",
    domain: "bitwarden.com",
  },
  {
    id: "dashlane",
    label: "Dashlane",
    description: "Reference repos, issues, logs, and deployment context.",
    category: "Development",
    status: "planned",
    domain: "dashlane.com",
  },
  {
    id: "zapier-tables",
    label: "Zapier Tables",
    description: "Reference assignments, grades, remaining work, and class updates.",
    category: "Education",
    status: "planned",
    domain: "zapier.com",
  },
  {
    id: "google-tasks",
    label: "Google Tasks",
    description: "Reference tasks, records, and workspace updates.",
    category: "Productivity",
    status: "planned",
    domain: "tasks.google.com",
  },
  {
    id: "apple-reminders",
    label: "Apple Reminders",
    description: "Reference messages, labels, and mailbox context.",
    category: "Email",
    status: "planned",
    domain: "icloud.com",
  },
  {
    id: "milanote",
    label: "Milanote",
    description: "Reference files, folders, and recent changes.",
    category: "Storage & Files",
    status: "planned",
    domain: "milanote.com",
  },
  {
    id: "whimsical",
    label: "Whimsical",
    description: "Reference events, due dates, and schedules.",
    category: "Calendar",
    status: "planned",
    domain: "whimsical.com",
  },
  {
    id: "lucidchart",
    label: "Lucidchart",
    description: "Reference documents, notes, and shared knowledge.",
    category: "Notes & Docs",
    status: "planned",
    domain: "lucid.co",
  },
  {
    id: "drawio",
    label: "draw.io",
    description: "Reference messages, channels, and conversation context.",
    category: "Communication",
    status: "planned",
    domain: "drawio.com",
  },
  {
    id: "plantuml",
    label: "PlantUML",
    description: "Reference posts, saved content, and creator activity.",
    category: "Social & Media",
    status: "planned",
    domain: "plantuml.com",
  },
  {
    id: "mermaid",
    label: "Mermaid",
    description: "Reference repos, issues, logs, and deployment context.",
    category: "Development",
    status: "planned",
    domain: "mermaid.js.org",
  },
  {
    id: "openai",
    label: "OpenAI",
    description: "Reference assignments, grades, remaining work, and class updates.",
    category: "Education",
    status: "planned",
    domain: "openai.com",
  },
  {
    id: "anthropic",
    label: "Anthropic",
    description: "Reference tasks, records, and workspace updates.",
    category: "Productivity",
    status: "planned",
    domain: "anthropic.com",
  },
  {
    id: "huggingface",
    label: "Hugging Face",
    description: "Reference messages, labels, and mailbox context.",
    category: "Email",
    status: "planned",
    domain: "huggingface.co",
  },
  {
    id: "kaggle",
    label: "Kaggle",
    description: "Reference files, folders, and recent changes.",
    category: "Storage & Files",
    status: "planned",
    domain: "kaggle.com",
  },
  {
    id: "colab",
    label: "Google Colab",
    description: "Reference events, due dates, and schedules.",
    category: "Calendar",
    status: "planned",
    domain: "colab.research.google.com",
  },
  {
    id: "jupyter",
    label: "Jupyter",
    description: "Reference documents, notes, and shared knowledge.",
    category: "Notes & Docs",
    status: "planned",
    domain: "jupyter.org",
  },
  {
    id: "observable",
    label: "Observable",
    description: "Reference messages, channels, and conversation context.",
    category: "Communication",
    status: "planned",
    domain: "observablehq.com",
  },
  {
    id: "tableau",
    label: "Tableau",
    description: "Reference posts, saved content, and creator activity.",
    category: "Social & Media",
    status: "planned",
    domain: "tableau.com",
  },
  {
    id: "powerbi",
    label: "Power BI",
    description: "Reference repos, issues, logs, and deployment context.",
    category: "Development",
    status: "planned",
    domain: "powerbi.microsoft.com",
  },
  {
    id: "looker",
    label: "Looker",
    description: "Reference assignments, grades, remaining work, and class updates.",
    category: "Education",
    status: "planned",
    domain: "lookerstudio.google.com",
  },
  {
    id: "metabase",
    label: "Metabase",
    description: "Reference tasks, records, and workspace updates.",
    category: "Productivity",
    status: "planned",
    domain: "metabase.com",
  },
  {
    id: "mode",
    label: "Mode",
    description: "Reference messages, labels, and mailbox context.",
    category: "Email",
    status: "planned",
    domain: "mode.com",
  },

  // --- Top popular picks across four sections ---
  // Productivity,
  {
    id: "google-meet",
    label: "Google Meet",
    description: "Reference Meet calls and recaps.",
    category: "Communication",
    status: "planned",
    domain: "meet.google.com",
  },
  {
    id: "facetime",
    label: "FaceTime",
    description: "Reference FaceTime calls.",
    category: "Communication",
    status: "planned",
    domain: "apple.com",
  },
  {
    id: "messenger",
    label: "Messenger",
    description: "Reference Messenger chats.",
    category: "Communication",
    status: "planned",
    domain: "messenger.com",
  },
  // Social & Media,
  {
    id: "youtube-music",
    label: "YouTube Music",
    description: "Reference your playlists and history.",
    category: "Social & Media",
    status: "planned",
    domain: "music.youtube.com",
  },
  {
    id: "snapchat",
    label: "Snapchat",
    description: "Reference memories and saved content.",
    category: "Social & Media",
    status: "planned",
    domain: "snapchat.com",
  },
];

export const CONNECTOR_CATEGORIES: ConnectorCategory[] = [
  "Productivity",
  "Email",
  "Storage & Files",
  "Calendar",
  "Notes & Docs",
  "Communication",
  "Education",
  "Social & Media",
  "Development",
];

/** Connectors a user can actually connect today. */
export const LIVE_CONNECTOR_IDS: ReadonlySet<string> = new Set(
  CONNECTOR_CATALOG.filter((item) => item.status === "live").map((item) => item.id),
);

/** Connectors whose code ships but need deployment credentials first. */
export const SETUP_REQUIRED_CONNECTOR_IDS: ReadonlySet<string> = new Set(
  CONNECTOR_CATALOG.filter((item) => item.status === "setup_required").map((item) => item.id),
);

export function getConnector(id: string): ConnectorItem | undefined {
  return CONNECTOR_CATALOG.find((item) => item.id === id);
}

/**
 * True only when this app can complete a connect flow for the entry right now.
 * A "live" entry without a `legacyProvider` has no wired flow, so it is not
 * actionable regardless of its label.
 */
export function isConnectorActionable(item: ConnectorItem): boolean {
  return item.status === "live" && !!item.legacyProvider;
}

/** Short, non-misleading label for a connector that cannot be connected yet. */
export function connectorUnavailableLabel(item: ConnectorItem): string {
  if (item.status === "setup_required") return "Requires setup";
  return "Not available yet";
}

/** Longer explanation, used for tooltips and screen-reader descriptions. */
export function connectorUnavailableReason(item: ConnectorItem): string {
  if (item.status === "setup_required") {
    return `${item.label} is implemented but this deployment has not been given ${item.label} credentials yet.`;
  }
  return `${item.label} is listed in the catalog. KovaGPT does not have a ${item.label} connection yet.`;
}
