const PUBLIC_SITEMAP_ENTRIES = Object.freeze(
  [
    { path: "/", changefreq: "weekly", priority: "1.0" },
    { path: "/images", changefreq: "weekly", priority: "0.8" },
    { path: "/pricing", changefreq: "monthly", priority: "0.8" },
    { path: "/modes", changefreq: "monthly", priority: "0.6" },
    { path: "/status", changefreq: "weekly", priority: "0.3" },
    { path: "/blog/best-ai-assistants", changefreq: "monthly", priority: "0.7" },
    { path: "/blog/ai-market-research-guide", changefreq: "monthly", priority: "0.7" },
    { path: "/blog/best-ai-market-research-tools", changefreq: "monthly", priority: "0.7" },
    { path: "/privacy", changefreq: "yearly", priority: "0.3" },
    { path: "/terms", changefreq: "yearly", priority: "0.3" },
    { path: "/refund", changefreq: "yearly", priority: "0.3" },
    { path: "/ai-safety", changefreq: "yearly", priority: "0.3" },
    { path: "/contact-support", changefreq: "yearly", priority: "0.4" },
    { path: "/getting-started", changefreq: "monthly", priority: "0.5" },
    { path: "/help", changefreq: "monthly", priority: "0.5" },
    { path: "/ai-image-generator", changefreq: "monthly", priority: "0.7" },
    { path: "/study-assistant", changefreq: "monthly", priority: "0.7" },
    { path: "/code-helper", changefreq: "monthly", priority: "0.7" },
    { path: "/ai-writer", changefreq: "monthly", priority: "0.7" },
    { path: "/research-assistant", changefreq: "monthly", priority: "0.7" },
    { path: "/chatgpt-alternative", changefreq: "monthly", priority: "0.7" },
    { path: "/ai-humanizer", changefreq: "monthly", priority: "0.7" },
    { path: "/humanize-ai-text", changefreq: "weekly", priority: "0.8" },
    ...[
      "/overview",
      "/features",
      "/features/deep-research",
      "/features/plugins",
      "/features/study-mode",
      "/features/chat-with-pdfs",
      "/plans",
      "/plans/free",
      "/plans/plus",
      "/plans/pro",
      "/business",
      "/business/ai-for-data-science-analytics",
      "/business/ai-for-engineering",
      "/business/ai-for-finance",
      "/business/ai-for-product-management",
      "/business/ai-for-sales-marketing",
      "/business/education",
      "/business/enterprise",
      "/education",
      "/college-students",
      "/families",
      "/parent-resources",
      "/use-cases",
      "/use-cases/chat-with-presentations",
      "/use-cases/chat-with-spreadsheets",
      "/use-cases/fitness-wellness-and-health",
      "/use-cases/money-and-finances",
      "/use-cases/recipes-cooking",
      "/use-cases/science-medicine",
      "/use-cases/students",
      "/use-cases/teachers",
      "/use-cases/travel-and-exploration",
      "/use-cases/university-educators",
      "/use-cases/veterans",
      "/health",
      "/shopping",
      "/shopping-assistant",
      "/translation",
      "/document-analysis",
      "/apps/google-drive",
      "/apps/gmail",
      "/apps/google-calendar",
      "/apps/github",
      "/apps/canva",
      "/apps/powerpoint",
      "/apps/spotify",
      "/codex",
      "/codex/enterprise",
      "/codex/pricing",
      "/download",
      "/features/voice",
      "/features/voice-with-video",
      "/import-to-chatgpt",
      "/merchants",
      "/plans/go",
      "/plans/k12-teachers",
      "/remote",
      "/voice",
      "/gpts",
      "/students/2026",
      "/translate/english-to-french",
      "/translate/english-to-hindi",
      "/translate/english-to-marathi",
      "/translate/english-to-portuguese",
      "/translate/english-to-tagalog",
      "/translate/english-to-tamil",
      "/translate/english-to-urdu",
      "/translate/hindi-to-english",
      "/translate/spanish-to-english",
      "/translate/tagalog-to-english",
      "/writing/paraphrase",
      "/about",
      "/mission",
      "/trust",
      "/transparency",
      "/model-behavior",
      "/moderation",
      "/data-controls",
      "/accessibility",
      "/contact-sales",
      "/academy",
      "/business-data",
      "/careers",
      "/charter",
      "/consumer-privacy",
      "/enterprise-privacy",
      "/open-models",
      "/our-structure",
      "/policies",
      "/safety",
      "/science",
      "/security-and-privacy",
      "/solutions",
      "/transparency-and-content-moderation",
      "/trust-and-transparency",
      "/solutions/blueprints/knowledge-retrieval",
      "/solutions/blueprints/mcpkit",
      "/solutions/industries/financial-services",
      "/solutions/industries/government",
      "/solutions/industries/healthcare",
      "/solutions/industries/retail",
      "/solutions/use-case/agents",
      "/solutions/use-case/coding",
      "/solutions/use-case/content-creation",
      "/solutions/use-case/data-analysis",
      "/solutions/use-case/research",
      "/academy/ai-fundamentals",
      "/academy/applications-of-ai",
      "/academy/brainstorming",
      "/academy/building-with-ai",
      "/academy/champion-programs",
      "/academy/chatgpt-for-education",
      "/academy/chatgpt-for-work",
      "/academy/chatgpt-sites",
      "/academy/chatgpt-work",
      "/academy/chatgpt-work/how-business-operations-teams-use-codex",
      "/academy/chatgpt-work/how-data-science-teams-use-codex",
      "/academy/chatgpt-work/how-sales-teams-use-codex",
      "/academy/codex",
      "/academy/custom-gpts",
      "/academy/customer-success",
      "/academy/data-analysis",
      "/academy/finance",
      "/academy/financial-services",
      "/academy/getting-started",
      "/academy/healthcare",
      "/academy/how-finance-teams-use-codex",
      "/academy/how-to-use-chatgpt-work-for-everyday-tasks",
      "/academy/image-generation",
      "/academy/managers",
      "/academy/marketing",
      "/academy/operations",
      "/academy/personalization",
      "/academy/projects",
      "/academy/research",
      "/academy/responsible-and-safe-use",
      "/academy/sales",
      "/academy/search-and-deep-research",
      "/academy/skills",
      "/academy/using-chatgpt",
      "/academy/what-is-ai",
      "/academy/working-with-files",
      "/academy/workspace-agents",
      "/academy/writing",
    ].map((path) => ({ path, changefreq: "monthly", priority: "0.6" })),
  ].map((entry) => Object.freeze(entry)),
);

const PUBLIC_REVIEW_PATHS = Object.freeze([
  ...new Set([
    ...PUBLIC_SITEMAP_ENTRIES.map(({ path }) => path),
    ...[
      "features",
      "plans",
      "business",
      "enterprise",
      "education",
      "families",
      "developers",
      "use-cases",
      "learn",
      "shopping-assistant",
      "translation",
      "document-analysis",
      "about",
      "mission",
      "press",
      "brand",
      "security",
      "trust",
      "transparency",
      "model-behavior",
      "moderation",
      "data-controls",
      "accessibility",
      "academy",
      "business-data",
      "careers",
      "charter",
      "consumer-privacy",
      "economic-research-exchange",
      "enterprise-privacy",
      "interview-guide",
      "open-model-feedback",
      "open-models",
      "our-structure",
      "policies",
      "residency",
      "safety",
      "science",
      "security-and-privacy",
      "solutions",
      "student-collective",
      "transparency-and-content-moderation",
      "trust-and-transparency",
    ].map((slug) => `/${slug}`),
    ...[
      "quickstart",
      "authentication",
      "api-reference",
      "models",
      "pricing",
      "usage-billing",
      "api-keys",
      "rate-limits",
      "errors",
      "streaming",
      "tool-calling",
      "image-generation",
      "files",
      "safety",
      "sdks",
      "examples",
      "migration-guides",
      "changelog",
      "status",
    ].map((slug) => `/developers/${slug}`),
    ...[
      "news",
      "product-updates",
      "engineering",
      "research",
      "safety-reports",
      "stories",
      "videos",
      "guides",
      "release-notes",
    ].map((section) => `/${section}`),
    "/changelog",
    "/engineering/server-owned-capabilities",
    "/safety-reports/truthful-preview-states",
    "/apps",
    "/assistants",
    ...["en", "es", "fr", "de", "pt-BR", "ja", "ko", "ar"].map((locale) => `/${locale}/home`),
    ...["ar", "de-DE", "es-419", "es-ES", "fr-CA", "fr-FR", "ja-JP", "ko-KR", "pt-BR", "pt-PT"].map(
      (locale) => `/${locale}`,
    ),
  ]),
]);

const PUBLIC_INDEXABLE_PATHS = new Set(PUBLIC_SITEMAP_ENTRIES.map((entry) => entry.path));
const NON_INDEXABLE_STATUSES = new Set(["error", "notFound", "redirected"]);

function normalizePathname(pathname) {
  if (typeof pathname !== "string" || !pathname.startsWith("/") || pathname.startsWith("//")) {
    return "";
  }

  const [withoutQuery = ""] = pathname.split(/[?#]/u, 1);
  if (withoutQuery === "/") return "/";
  return withoutQuery.replace(/\/+$/u, "");
}

function isPublicIndexableRoute(pathname, statuses = []) {
  if (statuses.some((status) => NON_INDEXABLE_STATUSES.has(status))) return false;
  return PUBLIC_INDEXABLE_PATHS.has(normalizePathname(pathname));
}

function robotsDirectiveForRoute(pathname, statuses = []) {
  return isPublicIndexableRoute(pathname, statuses) ? "index, follow" : "noindex, nofollow";
}

export {
  PUBLIC_SITEMAP_ENTRIES,
  PUBLIC_REVIEW_PATHS,
  isPublicIndexableRoute,
  normalizePathname,
  robotsDirectiveForRoute,
};
