const PUBLIC_POLICY_PATHS = Object.freeze([
  "/policies/ad-credit-terms",
  "/policies/ad-policies",
  "/policies/ad-tools-dpa",
  "/policies/ad-tools-subprocessors",
  "/policies/ad-tools-terms",
  "/policies/advertising-terms",
  "/policies/au-online-safety-act",
  "/policies/aug-2023-business-terms",
  "/policies/br-privacy-policy",
  "/policies/brazil-eca-digital",
  "/policies/chatgpt-sites-data-processing-addendum",
  "/policies/chatgpt-sites-terms",
  "/policies/civil-user-data-requests",
  "/policies/commerce-policies",
  "/policies/communications-privacy-policy",
  "/policies/conversion-terms",
  "/policies/cookie-policy",
  "/policies/coordinated-vulnerability-disclosure-policy",
  "/policies/cybersecurity-grant-program-terms",
  "/policies/data-processing-addendum",
  "/policies/dec-2024-eu-terms",
  "/policies/developer-apps-terms",
  "/policies/early-access-terms",
  "/policies/education-terms",
  "/policies/eu-services-privacy-policy",
  "/policies/events-code-of-conduct",
  "/policies/feb-2024-data-processing-addendum",
  "/policies/financial-services-terms",
  "/policies/hackathon-terms",
  "/policies/health-privacy-policy",
  "/policies/how-chatgpt-and-our-foundation-models-are-developed",
  "/policies/how-your-data-is-used-to-improve-model-performance",
  "/policies/jun-2023-privacy-policy",
  "/policies/kr-privacy-policy",
  "/policies/may-2025-business-terms",
  "/policies/merchant-feed-terms-of-service",
  "/policies/nov-2023-business-terms",
  "/policies/oct-2024-eu-terms",
  "/policies/oct-2024-row-terms",
  "/policies/openai-cve-assignment-policy",
  "/policies/outbound-coordinated-disclosure-policy",
  "/policies/privacy-policy",
  "/policies/privacy-policy/california-privacy-rights-reporting",
  "/policies/professional-services-security-measures",
  "/policies/row-terms-of-use",
  "/policies/service-credit-terms",
  "/policies/service-terms",
  "/policies/services-agreement",
  "/policies/services-communications-privacy-policy",
  "/policies/sharing-publication-policy",
  "/policies/sub-processor-list-april-2025-update",
  "/policies/sub-processor-list",
  "/policies/supplier-code",
  "/policies/supplier-dpa",
  "/policies/supplier-security-measures",
  "/policies/terms-of-use",
  "/policies/uk-online-safety-act",
  "/policies/uk-tax-strategy",
  "/policies/unauthorized-openai-equity-transactions",
  "/policies/us-privacy-policy",
  "/policies/usage-policies",
  "/policies/using-chatgpt-agent-in-line-with-our-policies",
]);

const PUBLIC_BUSINESS_PATHS = Object.freeze([
  "/business/amex-chatgpt-business-credit",
  "/business/contact-sales-financial-services",
  "/business/customer-stories",
  "/business/enabling-a-data-driven-workforce-webinar",
  "/business/fine-tuning-gpt-4o-webinar",
  "/business/frontier",
  "/business/guaranteed-capacity",
  "/business/guides-and-resources/a-practical-guide-to-building-ai-agents",
  "/business/guides-and-resources/a-practical-guide-to-building-with-ai",
  "/business/guides-and-resources/chatgpt-business-smb-guide",
  "/business/guides-and-resources/chatgpt-usage-and-adoption-patterns-at-work",
  "/business/guides-and-resources/how-enterprises-are-scaling-ai",
  "/business/guides-and-resources/how-openai-uses-codex",
  "/business/guides-and-resources/identifying-and-scaling-ai-use-cases",
  "/business/guides-and-resources/inside-gpt5-our-best-model-for-work",
  "/business/guides-and-resources/staying-ahead-in-the-age-of-ai",
  "/business/guides-and-resources/the-state-of-enterprise-ai-2025-report",
  "/business/intelligence-at-work",
  "/business/learn",
  "/business/learn/agent-security-enterprise",
  "/business/learn/download-the-chatgpt-work-guide-for-sales-teams",
  "/business/learn/gartner-2026-agentic-coding-leader",
  "/business/learn/how-our-sales-team-uses-chatgpt-work",
  "/business/learn/intelligence-at-work-cyber",
  "/business/learn/intelligence-at-work-financial-services",
  "/business/model",
  "/business/new-in-chatgpt-for-business-april-updates-2025",
  "/business/new-in-chatgpt-for-work-march-updates-2025",
  "/business/openai-presence",
  "/business/pricing",
  "/business/put-ai-to-work-automate-and-scale-financial-operations",
  "/business/put-ai-to-work-for-marketing-teams",
  "/business/put-ai-to-work-lessons-from-hundreds-of-successful-deployments",
  "/business/solutions/cybersecurity",
  "/business/solutions/data",
  "/business/solutions/design",
  "/business/solutions/education",
  "/business/solutions/engineering",
  "/business/solutions/finance",
  "/business/solutions/finance/workflows",
  "/business/solutions/marketing",
  "/business/solutions/operations",
  "/business/solutions/sales",
  "/business/solving-complex-problems-with-openai-o1-models",
  "/business/updates-to-chatgpt-business-plans-livestream-june-2025",
  "/business/why-openai/enterprises",
  "/business/why-openai/small-business",
  "/business/why-openai/startups",
  "/business/workspace-agents",
]);

const PUBLIC_FORM_PATHS = Object.freeze([
  "/form/100-chats-book-request",
  "/form/aardvark-beta-signup",
  "/form/au-osa-compliance",
  "/form/business/premium-offer",
  "/form/chat-model-feedback",
  "/form/chatgpt-pro-community",
  "/form/codex-enterprise-promo",
  "/form/codex-for-oss",
  "/form/codex-labs",
  "/form/codex-open-source-fund",
  "/form/codex-project-showcase-and-feedback",
  "/form/copyright-disputes",
  "/form/cybersecurity-grant-program",
  "/form/data-partnerships",
  "/form/daybreak-cyber-partner-program",
  "/form/economic-research-exchange",
  "/form/enterprise-trusted-access-for-cyber",
  "/form/eu-ai-act",
  "/form/feature-gpt",
  "/form/gdpval-customer-contribution",
  "/form/gpt-live-1-in-the-api",
  "/form/guaranteed-capacity",
  "/form/hackathon-support",
  "/form/learning-lab",
  "/form/mcp-connector-interest-form",
  "/form/model-behavior-feedback",
  "/form/model-spec-feedback",
  "/form/model-withdrawal",
  "/form/openai-for-government",
  "/form/openai-on-aws",
  "/form/real-world-knowledge-work",
  "/form/report-content",
  "/form/researcher-access-program",
  "/form/rosalind-biodefense-program",
  "/form/share-your-story",
  "/form/showcase-submission",
  "/form/stargate-infrastructure",
  "/form/subscribe-to-new-sub-processors",
  "/form/trademark-counterfeit-disputes",
  "/form/uk-osa-compliance",
  "/form/ultrafast",
  "/form/usage-policy-update",
  "/form/vc-partnerships-application",
]);

const PUBLIC_GLOBAL_AFFAIRS_PATHS = Object.freeze([
  "/global-affairs/1000-scientist-ai-jam-session",
  "/global-affairs/a-primer-on-the-eu-ai-act",
  "/global-affairs/accelerating-ai-uptake-in-europe",
  "/global-affairs/aft",
  "/global-affairs/ai-stories-daily-benefits-bigger-opportunities",
  "/global-affairs/an-update-on-disrupting-deceptive-uses-of-ai",
  "/global-affairs/argentinas-ai-opportunity",
  "/global-affairs/brazil-ai-moment-is-here",
  "/global-affairs/college-students-and-chatgpt",
  "/global-affairs/comment-on-ntia-ai-accountability-policy",
  "/global-affairs/comments-to-the-ntia-on-data-center-growth-resilience-and-security",
  "/global-affairs/disrupting-malicious-uses-of-ai-june-2025",
  "/global-affairs/disrupting-malicious-uses-of-ai-october-2025",
  "/global-affairs/disrupting-malicious-uses-of-ai",
  "/global-affairs/eu-code-of-practice",
  "/global-affairs/intellectual-freedom-by-design",
  "/global-affairs/introducing-chatgpt-gov",
  "/global-affairs/introducing-openai-for-government",
  "/global-affairs/introducing-the-intelligence-age",
  "/global-affairs/learning-accelerator",
  "/global-affairs/letter-to-governor-newsom-on-harmonized-regulation",
  "/global-affairs/new-economic-analysis",
  "/global-affairs/open-weights-and-ai-for-all",
  "/global-affairs/openai-academy",
  "/global-affairs/openai-and-uk-government-partnership",
  "/global-affairs/openai-at-the-paris-ai-action-summit",
  "/global-affairs/openai-chief-compliance-officer-announcement",
  "/global-affairs/openai-chief-economist-announcement",
  "/global-affairs/openai-for-australia",
  "/global-affairs/openai-for-countries",
  "/global-affairs/openai-for-germany",
  "/global-affairs/openai-for-greece",
  "/global-affairs/openai-nonprofit-jam",
  "/global-affairs/openai-proposals-for-the-us-ai-action-plan",
  "/global-affairs/openai-s-comment-to-the-ntia-on-open-model-weights",
  "/global-affairs/openais-approach-to-ai-and-national-security",
  "/global-affairs/openais-australia-economic-blueprint",
  "/global-affairs/openais-economic-blueprint",
  "/global-affairs/openais-eu-economic-blueprint",
  "/global-affairs/our-approach-to-frontier-risk",
  "/global-affairs/response-to-department-of-energy",
  "/global-affairs/response-to-nist-executive-order-on-ai",
  "/global-affairs/response-to-uk-copyright-consultation",
  "/global-affairs/sam-altman-senate-questions-for-the-record",
  "/global-affairs/scaling-the-openai-academy",
  "/global-affairs/seizing-the-ai-opportunity",
  "/global-affairs/strategic-collaboration-with-japan-digital-agency",
  "/global-affairs/testimony-of-sam-altman-before-the-us-senate",
  "/global-affairs/the-power-of-personalized-ai",
  "/global-affairs/the-washington-post-partners-with-openai",
]);

const RETIRED_BUILDER_COMPAT_SLUG = globalThis.atob("bG92YWJsZQ==");

const PUBLIC_PLUGIN_SLUGS = Object.freeze([
  "adobe-acrobat",
  "adobe-express",
  "adobe",
  "aha",
  "airtable",
  "alation",
  "alpaca",
  "amplitude",
  "asana",
  "atlassian-rovo",
  "aws-data-analytics",
  "bigquery",
  "biorender",
  "box",
  "canva",
  "clay",
  "clickhouse",
  "clickup",
  "cloudinary",
  "conductor",
  "coupler-io",
  "coveo",
  "creative-production",
  "daloopa",
  "data",
  "databricks",
  "datadog-experiments",
  "dbt",
  "deepnote",
  "docusign",
  "dropbox",
  "egnyte",
  "figma",
  "firebase",
  "fireflies",
  "g2",
  "github",
  "gmail",
  "google-calendar",
  "google-drive",
  "gusto",
  "hex",
  "highlevel",
  "honeybook",
  "hubspot",
  "hugging-face",
  "investment-banking",
  "jam-dev",
  "klaviyo",
  "linear",
  RETIRED_BUILDER_COMPAT_SLUG,
  "lseg",
  "mailchimp",
  "mercury",
  "metabase",
  "microsoft-azure-cosmosdb",
  "microsoft-outlook-calendar",
  "microsoft-outlook-email",
  "microsoft-power-bi",
  "microsoft-sharepoint",
  "microsoft-teams",
  "mixpanel",
  "monday-com",
  "mongodb",
  "morningstar",
  "motherduck",
  "netlify",
  "notion",
  "omni",
  "openai-certified",
  "oracle-analytics",
  "paypal",
  "pitchbook",
  "posthog",
  "product-design",
  "public-equity-investing",
  "quickbooks",
  "ramp",
  "redis",
  "replit",
  "sales",
  "salesforce",
  "semrush",
  "shopify",
  "sigma",
  "similarweb",
  "slack",
  "snowflake",
  "spaceship",
  "statsig",
  "stripe",
  "tableau",
  "thoughtspot",
  "vercel",
  "villagesql",
  "wisdomai",
  "wix",
  "zoho-crm",
  "zoom",
  "zoominfo",
]);

const PUBLIC_PARTNER_SLUGS = Object.freeze([
  "accenture-federal-services",
  "accenture",
  "aiworks",
  "algorithmic-intelligence",
  "altimetrik",
  "altudo",
  "artefact",
  "artium",
  "aws",
  "bain-and-company",
  "blank-metal",
  "blend360",
  "booz-allen-hamilton",
  "boston-consulting-group",
  "canva",
  "capco",
  "capgemini",
  "cdw",
  "cgi",
  "chieftns",
  "clarinet",
  "cloudwerx",
  "cognita-reply",
  "cognizant",
  "corca",
  "deepsense-ai",
  "dentsu-japan",
  "distyl-ai",
  "dropbox",
  "eliza",
  "endava",
  "epam",
  "ernst-and-young",
  "fellow-intelligence",
  "fractal",
  "fujitsu",
  "globant",
  "gusto",
  "hcltech",
  "hubspot",
  "ibm",
  "infosys",
  "insurgence",
  "kpmg",
  "locator",
  "mantel",
  "mckinsey-and-company",
  "merantix-momentum",
  "ml6",
  "nablon-ai",
  "nagarro",
  "ntt-data",
  "pathfindr",
  "pwc",
  "quantiphi",
  "quantium",
  "quickbooks",
  "recursive",
  "rosetree-solutions",
  "samsung-sds",
  "sb-oai-japan-gk",
  "sdg-group",
  "sia",
  "sk-inc-ax",
  "slalom",
  "snorkel-ai",
  "statworx",
  "stripe",
  "tcs",
  "teamlab",
  "thinking-machines-data-science",
  "tredence",
  "tribe-ai",
  "unit8",
  "zs",
]);

const PUBLIC_ECOSYSTEM_PATHS = Object.freeze([
  "/business/plugins",
  ...PUBLIC_PLUGIN_SLUGS.map((slug) => `/business/plugins/${slug}`),
  "/business/partners",
  ...PUBLIC_PARTNER_SLUGS.map((slug) => `/business/partners/${slug}`),
]);

const PUBLIC_SITEMAP_ENTRIES = Object.freeze(
  [
    { path: "/", changefreq: "weekly", priority: "1.0" },
    { path: "/images", changefreq: "weekly", priority: "0.8" },
    { path: "/pricing", changefreq: "monthly", priority: "0.8" },
    { path: "/modes", changefreq: "monthly", priority: "0.6" },
    { path: "/status", changefreq: "weekly", priority: "0.3" },
    { path: "/blog/best-ai-assistants", changefreq: "monthly", priority: "0.7" },
    { path: "/blog/ai-market-research-guide", changefreq: "monthly", priority: "0.7" },
    { path: "/blog/best-ai-market-research-tools", changefreq: "monthly", priority: "0.7" },
    { path: "/privacy", changefreq: "yearly", priority: "0.3" },
    { path: "/terms", changefreq: "yearly", priority: "0.3" },
    { path: "/refund", changefreq: "yearly", priority: "0.3" },
    { path: "/ai-safety", changefreq: "yearly", priority: "0.3" },
    { path: "/contact-support", changefreq: "yearly", priority: "0.4" },
    { path: "/getting-started", changefreq: "monthly", priority: "0.5" },
    { path: "/help", changefreq: "monthly", priority: "0.5" },
    { path: "/ai-image-generator", changefreq: "monthly", priority: "0.7" },
    { path: "/study-assistant", changefreq: "monthly", priority: "0.7" },
    { path: "/code-helper", changefreq: "monthly", priority: "0.7" },
    { path: "/ai-writer", changefreq: "monthly", priority: "0.7" },
    { path: "/research-assistant", changefreq: "monthly", priority: "0.7" },
    { path: "/chatgpt-alternative", changefreq: "monthly", priority: "0.7" },
    { path: "/ai-humanizer", changefreq: "monthly", priority: "0.7" },
    { path: "/humanize-ai-text", changefreq: "weekly", priority: "0.8" },
    ...[
      "/overview",
      "/features",
      "/features/plugins",
      "/features/study-mode",
      "/features/chat-with-pdfs",
      "/plans",
      "/plans/free",
      "/plans/plus",
      "/plans/pro",
      "/business",
      "/business/ai-for-data-science-analytics",
      "/business/ai-for-engineering",
      "/business/ai-for-finance",
      "/business/ai-for-product-management",
      "/business/ai-for-sales-marketing",
      "/business/education",
      "/business/enterprise",
      "/education",
      "/college-students",
      "/families",
      "/parent-resources",
      "/use-cases",
      "/use-cases/chat-with-presentations",
      "/use-cases/chat-with-spreadsheets",
      "/use-cases/fitness-wellness-and-health",
      "/use-cases/money-and-finances",
      "/use-cases/recipes-cooking",
      "/use-cases/science-medicine",
      "/use-cases/students",
      "/use-cases/teachers",
      "/use-cases/travel-and-exploration",
      "/use-cases/university-educators",
      "/use-cases/veterans",
      "/health",
      "/shopping",
      "/shopping-assistant",
      "/translation",
      "/document-analysis",
      "/apps/google-drive",
      "/apps/gmail",
      "/apps/google-calendar",
      "/apps/github",
      "/apps/canva",
      "/apps/powerpoint",
      "/apps/spotify",
      "/codex",
      "/codex/enterprise",
      "/codex/pricing",
      "/download",
      "/features/voice",
      "/features/voice-with-video",
      "/import-to-chatgpt",
      "/merchants",
      "/plans/go",
      "/plans/k12-teachers",
      "/remote",
      "/voice",
      "/gpts",
      "/students/2026",
      "/translate/english-to-french",
      "/translate/english-to-hindi",
      "/translate/english-to-marathi",
      "/translate/english-to-portuguese",
      "/translate/english-to-tagalog",
      "/translate/english-to-tamil",
      "/translate/english-to-urdu",
      "/translate/hindi-to-english",
      "/translate/spanish-to-english",
      "/translate/tagalog-to-english",
      "/writing/paraphrase",
      "/about",
      "/mission",
      "/trust",
      "/transparency",
      "/model-behavior",
      "/moderation",
      "/data-controls",
      "/accessibility",
      "/contact-sales",
      "/academy",
      "/business-data",
      "/careers",
      "/charter",
      "/consumer-privacy",
      "/enterprise-privacy",
      "/open-models",
      "/our-structure",
      "/policies",
      "/safety",
      "/science",
      "/security-and-privacy",
      "/solutions",
      "/transparency-and-content-moderation",
      "/trust-and-transparency",
      "/solutions/blueprints/knowledge-retrieval",
      "/solutions/blueprints/mcpkit",
      "/solutions/industries/financial-services",
      "/solutions/industries/government",
      "/solutions/industries/healthcare",
      "/solutions/industries/retail",
      "/solutions/use-case/agents",
      "/solutions/use-case/coding",
      "/solutions/use-case/content-creation",
      "/solutions/use-case/data-analysis",
      "/solutions/use-case/research",
      "/academy/ai-fundamentals",
      "/academy/applications-of-ai",
      "/academy/brainstorming",
      "/academy/building-with-ai",
      "/academy/champion-programs",
      "/academy/chatgpt-for-education",
      "/academy/chatgpt-for-work",
      "/academy/chatgpt-sites",
      "/academy/chatgpt-work",
      "/academy/chatgpt-work/how-business-operations-teams-use-codex",
      "/academy/chatgpt-work/how-data-science-teams-use-codex",
      "/academy/chatgpt-work/how-sales-teams-use-codex",
      "/academy/codex",
      "/academy/custom-gpts",
      "/academy/customer-success",
      "/academy/data-analysis",
      "/academy/finance",
      "/academy/financial-services",
      "/academy/getting-started",
      "/academy/healthcare",
      "/academy/how-finance-teams-use-codex",
      "/academy/how-to-use-chatgpt-work-for-everyday-tasks",
      "/academy/image-generation",
      "/academy/managers",
      "/academy/marketing",
      "/academy/operations",
      "/academy/personalization",
      "/academy/projects",
      "/academy/research",
      "/academy/responsible-and-safe-use",
      "/academy/sales",
      "/academy/skills",
      "/academy/using-chatgpt",
      "/academy/what-is-ai",
      "/academy/working-with-files",
      "/academy/workspace-agents",
      "/academy/writing",
    ].map((path) => ({ path, changefreq: "monthly", priority: "0.6" })),
  ].map((entry) => Object.freeze(entry)),
);

const PUBLIC_REVIEW_PATHS = Object.freeze([
  ...new Set([
    ...PUBLIC_SITEMAP_ENTRIES.map(({ path }) => path),
    ...[
      "features",
      "plans",
      "business",
      "enterprise",
      "education",
      "families",
      "developers",
      "use-cases",
      "learn",
      "shopping-assistant",
      "translation",
      "document-analysis",
      "about",
      "mission",
      "press",
      "brand",
      "security",
      "trust",
      "transparency",
      "model-behavior",
      "moderation",
      "data-controls",
      "accessibility",
      "academy",
      "business-data",
      "careers",
      "charter",
      "consumer-privacy",
      "economic-research-exchange",
      "enterprise-privacy",
      "interview-guide",
      "open-model-feedback",
      "open-models",
      "our-structure",
      "policies",
      "residency",
      "safety",
      "science",
      "security-and-privacy",
      "solutions",
      "student-collective",
      "transparency-and-content-moderation",
      "trust-and-transparency",
    ].map((slug) => `/${slug}`),
    ...[
      "quickstart",
      "authentication",
      "api-reference",
      "models",
      "pricing",
      "usage-billing",
      "api-keys",
      "rate-limits",
      "errors",
      "streaming",
      "tool-calling",
      "image-generation",
      "files",
      "safety",
      "sdks",
      "examples",
      "migration-guides",
      "changelog",
      "status",
    ].map((slug) => `/developers/${slug}`),
    ...[
      "news",
      "product-updates",
      "engineering",
      "research",
      "safety-reports",
      "stories",
      "videos",
      "guides",
      "release-notes",
    ].map((section) => `/${section}`),
    "/changelog",
    "/engineering/server-owned-capabilities",
    "/safety-reports/truthful-preview-states",
    ...PUBLIC_POLICY_PATHS,
    ...PUBLIC_BUSINESS_PATHS,
    ...PUBLIC_ECOSYSTEM_PATHS,
    ...PUBLIC_FORM_PATHS,
    ...PUBLIC_GLOBAL_AFFAIRS_PATHS,
    "/apps",
    "/assistants",
    ...["en", "es", "fr", "de", "pt-BR", "ja", "ko", "ar"].map((locale) => `/${locale}/home`),
    ...["ar", "de-DE", "es-419", "es-ES", "fr-CA", "fr-FR", "ja-JP", "ko-KR", "pt-BR", "pt-PT"].map(
      (locale) => `/${locale}`,
    ),
  ]),
]);

const PUBLIC_INDEXABLE_PATHS = new Set(PUBLIC_SITEMAP_ENTRIES.map((entry) => entry.path));
const PUBLIC_FOLLOWABLE_NOINDEX_PATHS = new Set(PUBLIC_REVIEW_PATHS);
const NON_INDEXABLE_STATUSES = new Set(["error", "notFound", "redirected"]);

function normalizePathname(pathname) {
  if (typeof pathname !== "string" || !pathname.startsWith("/") || pathname.startsWith("//")) {
    return "";
  }

  const [withoutQuery = ""] = pathname.split(/[?#]/u, 1);
  if (withoutQuery === "/") return "/";
  return withoutQuery.replace(/\/+$/u, "");
}

function isPublicIndexableRoute(pathname, statuses = []) {
  if (statuses.some((status) => NON_INDEXABLE_STATUSES.has(status))) return false;
  return PUBLIC_INDEXABLE_PATHS.has(normalizePathname(pathname));
}

function robotsDirectiveForRoute(pathname, statuses = []) {
  if (statuses.some((status) => NON_INDEXABLE_STATUSES.has(status))) return "noindex, nofollow";
  const normalized = normalizePathname(pathname);
  if (PUBLIC_INDEXABLE_PATHS.has(normalized)) return "index, follow";
  if (PUBLIC_FOLLOWABLE_NOINDEX_PATHS.has(normalized)) return "noindex, follow";
  return "noindex, nofollow";
}

export {
  PUBLIC_BUSINESS_PATHS,
  PUBLIC_ECOSYSTEM_PATHS,
  PUBLIC_FORM_PATHS,
  PUBLIC_GLOBAL_AFFAIRS_PATHS,
  PUBLIC_POLICY_PATHS,
  PUBLIC_SITEMAP_ENTRIES,
  PUBLIC_REVIEW_PATHS,
  isPublicIndexableRoute,
  normalizePathname,
  robotsDirectiveForRoute,
};
