import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy - KovaGPT" },
      { name: "description", content: "How KovaGPT collects, uses, stores, and protects your data." },
      { property: "og:title", content: "Privacy Policy - KovaGPT" },
      { property: "og:description", content: "How KovaGPT collects, uses, stores, and protects your data." },
    ],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16 prose prose-invert">
      <h1>Privacy Policy</h1>
      <p className="text-sm opacity-70">Last updated: {new Date().getFullYear()}</p>

      <h2>1. What we collect</h2>
      <p>When you create a KovaGPT account we collect your email address and (if you sign in with a provider) your provider profile basics. When you chat, generate images, upload files, or use voice features we receive the content you submit so we can produce a response.</p>

      <h2>2. How we use it</h2>
      <p>We use your data to operate KovaGPT: route prompts to AI models, generate images, transcribe voice, store your conversation history, and enforce usage limits per plan. We do not sell your data.</p>

      <h2>3. Chats &amp; uploads</h2>
      <p>Chat history is stored on your device and (where you are signed in) on our backend so you can continue conversations across sessions. Uploaded files are processed to answer your prompt and are scoped to your account. Do not upload content you are not authorized to share.</p>

      <h2>4. Payments</h2>
      <p>Subscriptions are processed by Stripe. We never see or store your card number; we only receive a Stripe customer/subscription identifier and the resulting plan status.</p>

      <h2>5. AI accuracy</h2>
      <p>KovaGPT responses are generated by large language and image models and may be incorrect, incomplete, or out of date. Do not rely on KovaGPT for medical, legal, financial, or safety‑critical decisions without independent verification.</p>

      <h2>6. Account deletion</h2>
      <p>You can request deletion of your account and associated data at any time by emailing <a href="mailto:support@kovagpt.com">support@kovagpt.com</a>. We will remove your account and personal data within 30 days, except where retention is required by law (e.g. payment records).</p>

      <h2>7. Security</h2>
      <p>Data is transmitted over HTTPS and stored in managed cloud infrastructure with row‑level access controls. No system is perfectly secure; use a strong, unique password.</p>

      <h2>8. Children</h2>
      <p>KovaGPT is not directed at children under 13 and we do not knowingly collect data from them.</p>

      <h2>9. Changes</h2>
      <p>We may update this policy. Material changes will be announced in‑product or by email.</p>

      <p className="mt-8"><Link to="/">← Back to KovaGPT</Link> · <Link to="/terms">Terms of Service</Link></p>
    </main>
  );
}
