import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — KovaGPT" },
      { name: "description", content: "The rules for using KovaGPT, including payments, acceptable use, and AI accuracy." },
      { property: "og:title", content: "Terms of Service — KovaGPT" },
      { property: "og:description", content: "The rules for using KovaGPT, including payments, acceptable use, and AI accuracy." },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16 prose prose-invert">
      <h1>Terms of Service</h1>
      <p className="text-sm opacity-70">Last updated: {new Date().getFullYear()}</p>

      <h2>1. Your account</h2>
      <p>You must be at least 13 years old to use KovaGPT. You are responsible for activity under your account and for keeping your credentials safe.</p>

      <h2>2. Acceptable use</h2>
      <p>Don't use KovaGPT to: generate or distribute illegal content; harass, defraud, or impersonate others; create malware or attempt to break our systems; generate CSAM or sexual content involving minors; produce content that infringes others' intellectual property; or attempt to extract, resell, or train on our model outputs at scale. We may suspend or terminate accounts that violate these rules.</p>

      <h2>3. Chats &amp; uploads</h2>
      <p>You retain ownership of the content you submit. You grant KovaGPT a limited license to process that content to provide the service. Don't upload content you don't have the right to share.</p>

      <h2>4. Payments &amp; refunds</h2>
      <p>Paid plans renew automatically until cancelled. You can cancel at any time from your account; access continues until the end of the paid period. Charges are generally non‑refundable except where required by law.</p>

      <h2>5. AI accuracy</h2>
      <p>KovaGPT outputs are generated by AI and may be inaccurate, incomplete, biased, or offensive. You are responsible for reviewing outputs before relying on them. KovaGPT is not a substitute for professional advice.</p>

      <h2>6. Usage limits</h2>
      <p>Each plan has fair‑use limits on chats, image generations, file uploads, and voice. We may throttle or temporarily block requests that exceed these limits or that we reasonably believe are abusive or automated.</p>

      <h2>7. Account deletion</h2>
      <p>You can delete your account at any time by emailing <a href="mailto:support@kovagpt.com">support@kovagpt.com</a>. We may also terminate accounts for breach of these terms.</p>

      <h2>8. Disclaimers &amp; liability</h2>
      <p>KovaGPT is provided "as is" without warranties of any kind. To the maximum extent permitted by law, our aggregate liability for any claim is limited to the amount you paid us in the 12 months before the claim.</p>

      <h2>9. Changes</h2>
      <p>We may update these terms. Continued use after changes means you accept the updated terms.</p>

      <p className="mt-8"><Link to="/">← Back to KovaGPT</Link> · <Link to="/privacy">Privacy Policy</Link></p>
    </main>
  );
}
