-- Project Forge: provenance, immutable audit, activity, relationships and reference-aware cleanup.
alter table public.agent_deliverables add column if not exists deleted_at timestamptz, add column if not exists purge_after timestamptz, add column if not exists cleanup_status text not null default 'none' check(cleanup_status in('none','blocked','pending','complete','failed')), add column if not exists restored_from_id uuid references public.agent_deliverables(id);
create table public.agent_resource_promotions(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,deliverable_id uuid not null references public.agent_deliverables(id),source_revision integer not null,run_id uuid not null references public.agent_jobs(id),specialist_task_id text,project_id uuid references public.projects(id),destination_type text not null check(destination_type in('project_file','project_artifact','research_report','library_document','context_pack')),destination_id uuid,idempotency_key text not null,mode text not null check(mode in('create','replace','revision')),status text not null check(status in('pending','completed','failed','cleanup_pending')),integrity_hash text not null,evidence jsonb not null default '[]',approved_by uuid not null references auth.users(id),created_at timestamptz not null default now(),completed_at timestamptz,redacted_error jsonb,unique(owner_id,idempotency_key));
create table public.agent_resource_relationships(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,project_id uuid references public.projects(id),source_type text not null,source_id uuid not null,relationship text not null,target_type text not null,target_id uuid not null,created_at timestamptz not null default now(),unique(owner_id,source_type,source_id,relationship,target_type,target_id));
create table public.agent_resource_activity(id bigint generated always as identity primary key,owner_id uuid not null references auth.users(id) on delete cascade,project_id uuid references public.projects(id),actor_id uuid not null references auth.users(id),action text not null,safe_label text not null,source_run_id uuid references public.agent_jobs(id),deliverable_id uuid references public.agent_deliverables(id),destination_type text,destination_id uuid,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.agent_resource_audit(id bigint generated always as identity primary key,owner_id uuid not null references auth.users(id) on delete cascade,actor_id uuid not null references auth.users(id),source_run_id uuid references public.agent_jobs(id),deliverable_id uuid references public.agent_deliverables(id),source_revision integer,destination_type text,destination_id uuid,action text not null,success boolean not null,approval_id uuid references public.agent_approvals(id),redacted_error jsonb,created_at timestamptz not null default now());
alter table public.agent_resource_promotions enable row level security;alter table public.agent_resource_relationships enable row level security;alter table public.agent_resource_activity enable row level security;alter table public.agent_resource_audit enable row level security;
create policy "Owners read promotions" on public.agent_resource_promotions for select using(auth.uid()=owner_id);create policy "Owners read resource relationships" on public.agent_resource_relationships for select using(auth.uid()=owner_id);create policy "Owners read resource activity" on public.agent_resource_activity for select using(auth.uid()=owner_id);create policy "Owners read resource audit" on public.agent_resource_audit for select using(auth.uid()=owner_id);
create or replace function public.promote_agent_deliverable(p_deliverable_id uuid,p_destination_type text,p_project_id uuid,p_mode text,p_idempotency_key text,p_confirm_replace boolean default false) returns jsonb language plpgsql security definer set search_path=public as $$
declare d agent_deliverables%rowtype; destination uuid; promotion uuid; existing agent_resource_promotions%rowtype;
begin
 select * into existing from agent_resource_promotions where owner_id=auth.uid() and idempotency_key=p_idempotency_key;if found then return jsonb_build_object('promotion_id',existing.id,'destination_id',existing.destination_id,'status',existing.status,'idempotent',true);end if;
 select * into d from agent_deliverables where id=p_deliverable_id and owner_id=auth.uid() and status<>'deleted' for update;if not found then raise exception 'Deliverable not found';end if;
 if p_mode in('replace','revision') and not p_confirm_replace then raise exception 'Explicit replacement confirmation required';end if;
 if p_destination_type='project_file' then if not exists(select 1 from project_members where project_id=p_project_id and user_id=auth.uid() and role in('owner','editor')) then raise exception 'Project editor access required';end if;insert into project_files(project_id,name,storage_path,mime_type,size_bytes,kind,uploaded_by) values(p_project_id,d.title,split_part(d.storage_reference,':',2),d.mime_type,0,'agent-deliverable',auth.uid()) returning id into destination;
 elsif p_destination_type='library_document' then insert into user_library_items(user_id,title,item_type,source,file_type,file_url,metadata) values(auth.uid(),d.title,'document','agent-deliverable',d.mime_type,d.storage_reference,jsonb_build_object('deliverable_id',d.id,'run_id',d.run_id,'revision',d.revision,'integrity_hash',d.integrity_hash)) returning id into destination;
 else raise exception 'Destination resource table is not available';end if;
 insert into agent_resource_promotions(owner_id,deliverable_id,source_revision,run_id,specialist_task_id,project_id,destination_type,destination_id,idempotency_key,mode,status,integrity_hash,evidence,approved_by,completed_at) values(auth.uid(),d.id,d.revision,d.run_id,d.specialist_task_id,p_project_id,p_destination_type,destination,p_idempotency_key,p_mode,'completed',d.integrity_hash,d.source_evidence,auth.uid(),now()) returning id into promotion;
 insert into agent_resource_activity(owner_id,project_id,actor_id,action,safe_label,source_run_id,deliverable_id,destination_type,destination_id) values(auth.uid(),p_project_id,auth.uid(),'resource_promoted',d.title,d.run_id,d.id,p_destination_type,destination);
 insert into agent_resource_audit(owner_id,actor_id,source_run_id,deliverable_id,source_revision,destination_type,destination_id,action,success) values(auth.uid(),auth.uid(),d.run_id,d.id,d.revision,p_destination_type,destination,'promotion',true);
 return jsonb_build_object('promotion_id',promotion,'destination_id',destination,'status','completed','idempotent',false);
end $$;grant execute on function public.promote_agent_deliverable(uuid,text,uuid,text,text,boolean) to authenticated;
