// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { optionalUser } from "@/lib/api-auth.server";

function failAuthentication(status: number, error: string): never {
  throw Response.json(
    { error },
    {
      status,
      headers: { "Cache-Control": "no-store" },
    },
  );
}

export const requireSupabaseAuth = createMiddleware({
  type: "function",
}).server(async ({ next }) => {
  // Reject anonymous and malformed credentials before reading deployment
  // configuration. Public signed-out pages must not disclose configuration
  // state or turn an ordinary 401 into a noisy 500 when auth is unavailable.
  const request = getRequest();
  if (!request?.headers) failAuthentication(401, "Unauthorized");

  const auth = await optionalUser(request);
  if (!auth) failAuthentication(401, "Unauthorized");
  if (auth instanceof Response) {
    failAuthentication(
      auth.status,
      auth.status === 503 ? "Authentication unavailable" : "Unauthorized",
    );
  }

  return next({
    context: {
      supabase: auth.supabaseUser,
      userId: auth.userId,
      claims: auth.claims ?? {},
    },
  });
});
