// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

type BrowserRuntimeEnv = Record<string, string | undefined>;

function readRuntimeEnv(): BrowserRuntimeEnv {
  return typeof process !== "undefined" && process.env ? process.env : {};
}

function supabaseUrl(): string | undefined {
  const runtimeEnv = readRuntimeEnv();
  return import.meta.env.VITE_SUPABASE_URL || runtimeEnv.SUPABASE_URL;
}

function supabasePublishableKey(): string | undefined {
  const runtimeEnv = readRuntimeEnv();
  return (
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    runtimeEnv.SUPABASE_PUBLISHABLE_KEY ||
    runtimeEnv.SUPABASE_ANON_KEY
  );
}

export function getSupabaseClientConfigStatus() {
  const url = supabaseUrl();
  const key = supabasePublishableKey();
  return {
    configured: Boolean(url && key),
    missing: [
      !url ? "VITE_SUPABASE_URL" : null,
      !key ? "VITE_SUPABASE_PUBLISHABLE_KEY" : null,
    ].filter(Boolean) as string[],
  };
}

function createSupabaseClient() {
  const SUPABASE_URL = supabaseUrl();
  const SUPABASE_PUBLISHABLE_KEY = supabasePublishableKey();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
<<<<<<< HEAD
    const missing = getSupabaseClientConfigStatus().missing;
    const message = `Supabase browser auth is unavailable because deployment configuration is missing: ${missing.join(", ")}.`;
=======
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Configure Supabase environment variables for this deployment.`;
>>>>>>> origin/main
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
